icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
if_command = "false"
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
if_command = "false"
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
format = " $icon root: $available.eng(w:2) "

[[block]]
if_command = "false"
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
format = " $icon $ssid[$signal_strength] "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
