#!/usr/bin/env bash

# TODO: get floats working

die() {
	log "$@"
	exit 1
}

raw_log() {
	printf "$@" >> $logfile ||
		printf 'printf failed: %s\n' "$*" >> $logfile
}

log() {
	if [[ $last_log ]]; then
		last_log=''
		raw_log '\n'
	fi
	raw_log "$@"
}

log_time() {
	log '%(%Y-%m-%d %H:%M:%S)T\n'
}

log_printf() {
	log "$@"
	printf "$@"
}

log_out_chars() {
	local i 
	for(( i=0 ; i<${#1} ; i++ )); do
		log_out_char ${1:$i:1}
	done
}

log_out_char() {
	local x

	printf -v x '%d' "'$1"
	printf -v x '%02x' $x
	log_out_byte $x
}

log_out_byte() {
	# return
	if [[ $last_log != '>' ]]; then
		raw_log '\n>'
		last_log='>'
	fi
	raw_log ' %s' $1
}

log_in_char() {
	local x

	printf -v x '%d' "'$1"
	printf -v x '%02x' $x
	log_in_byte $x
}

log_in_byte() {
	# return
	if [[ $last_log != '<' ]]; then
		raw_log '\n<'
		last_log='<'
	fi
	raw_log ' %s' $1
}

log_array() {
	local name=$1
	local -n _a=$name
	local _i

	log 'Array %s\n' $name
	for _i in ${!_a[@]}; do
		log '%s[%s]=%s\n' $name $_i "${_a[$_i]}"
	done
}


####################
# Helpers for mapping atom names to values
# Some atoms are defined by the core protocol so we can
# cache their mappings early
# Others we have to get the server to generate an id (intern_atom)
# for an atom name and add that to the list of mappings
####################

cache_xa_names() {
	local names=( ATOM CARDINAL COLORMAP CARDINAL INTEGER PIXMAP \
		STRING VISUALID WINDOW WM_COMMAND WM_HINTS WM_NAME \
		WM_NORMAL_HINTS WM_SIZE_HINTS WM_CLASS WM_TRANSIENT_FOR )
	local name xa_id

	for name in ${names[@]}; do
		xa_id="XA_$name"
		xa_names[${!xa_id}]=$name
	done
}

xa_name() {
	xa_id=$1
	echo ${xa_names[xa_id]:-$xa_id}
}

intern_atoms() {
	intern_atom UTF8_STRING
	intern_atom WM_PROTOCOLS
	intern_atom WM_TAKE_FOCUS
	intern_atom WM_DELETE_WINDOW
	intern_atom _NET_CURRENT_DESKTOP
	intern_atom _NET_NUMBER_OF_DESKTOPS
	intern_atom _NET_DESKTOP_VIEWPORT
	intern_atom _NET_WORKAREA
	intern_atom _NET_SUPPORTED
	intern_atom _NET_ACTIVE_WINDOW
	intern_atom _NET_SUPPORTING_WM_CHECK
	intern_atom _NET_WM_NAME
	intern_atom _NET_WM_STATE
	intern_atom _NET_WM_STATE_FULLSCREEN
	intern_atom _NET_WM_WINDOW_TYPE
	intern_atom _NET_WM_WINDOW_TYPE_NORMAL
	intern_atom _NET_WM_STRUT_PARTIAL
	intern_atom _NET_CLIENT_LIST
}

intern_atom() {
	local atom=$1

	x_send_intern_atom $atom set_atom_value
}


set_atom_value() {
	local name=$1
	local atom=$2

	local root=${x_screen_0['root']}
	local xaname=$name

	[[ ${xaname::1} == '_' ]] || xaname="_$xaname"
	xaname="XA$xaname"
	printf -v $xaname $atom
	xa_names[atom]=$name

	case $name in
		_NET_CURRENT_DESKTOP) 
			x_send_change_property $root $X_PropModeReplace $atom $XA_CARDINAL 32 1 $wm_current_desktop 
			;;
		_NET_NUMBER_OF_DESKTOPS) 
			x_send_change_property $root $X_PropModeReplace $atom $XA_CARDINAL 32 1 $wm_desktop_count
			;;
		WM_PROTOCOLS)
			wm_property_change_handlers[XA_WM_PROTOCOLS]=wm_protocols_changed
	esac
}

# This is the other way round than the rest of the atom helpers
# When we get monitor info we get an atom id but no name
# so the monitor code asks for the name, and this is the callback
set_atom_name() {
	local atom=$1
	local name=$2

	xa_names[$atom]=$name
}


####################
# Load XRandR extension, check version then get monitor information
# Monitor changes trigger a ConfigureNotify event where the root
# is both the event source and window target
####################

rr_get_monitors() {
	x_send_query_extension $X_RANDR_NAME rr_query_version
}

rr_query_version() {
	local name=$1
	local present=$2

	if (( present == 0 )); then
		rr_setup_failed
	else
		x_send_rr_query_version rr_setup
	fi
}

rr_setup() {
	local status=$1

	if (( status == X_RROk )); then
		x_send_rr_get_monitors update_monitors
	else
		rr_setup_failed
	fi
}

rr_setup_failed() {
	log 'XRandR extension not present or version not supported\n'
	log 'Using entire screen\n'

	x_screen_0['primary']=0
	wm_monitors=( 0 )

	default_monitor_config
	desktop_monitor_config

	layout_monitor 0

	update_net_workarea
	update_net_viewport
}

handle_configure_notify() {
	local windowid=$1
	local event=$2

	local root=${x_screen_0['root']}

	log '< ConfigureNotify for event %s window %s\n' $event $windowid

	# When xrandr changes monitor/output config root gets a ConfigureNotify
	# We can get lots in a short period as outputs/crtcs get unconfigured 
	# and then reconfigured 
	# The event loop will only request the updated monitor configuration
	# when there are no pending replies or events
	(( event == root && windowid == root )) && request_get_monitors
}


####################
# Get kayboard mapping and grab keys that we use for commands
# Handle key press events to call those commands
####################

get_key_mappings() {
	x_send_get_keyboard_mapping grab_command_keys
}

grab_command_keys() {
	# key_map passed by name
	# key_map[keycode]=keysym
	local -n key_map=$1
	local keycode keysym keycommands keycmds keycmd mask

	for keycode in ${!key_map[@]}; do
		keysym=${key_map[$keycode]}
		keycommands=${wm_keysym_commands[$keysym]}
		[[ $keycommands ]] || continue
		wm_keycode_commands[$keycode]="$keycommands"
		IFS=',' read -ra keycmds <<< "$keycommands" 
		for keycmd in "${keycmds[@]}"; do
			mask="${keycmd%:*}"
			x_send_grab_key $keycode $mask
		done
	done
}

handle_key_press() {
	local keycode=$1
	local keymask=$2

	log 'KeyPress %s' $keycode 

	keycode_cmd="${wm_keycode_commands[keycode]}" 

	log 'Key commands %s\n' "$keycode_cmd"

	[[ $keycode_cmd ]] || return 0

	IFS=',' read -ra keycmds <<< "$keycode_cmd"
	for keycmd in "${keycmds[@]}"; do

		log 'Key command %s\n' "$keycmd"

		mask="${keycmd%:*}"

		log 'Event Mask %s, Key Mask %s\n' "$mask" "$keymask"

		(( mask == keymask )) || continue

		cmd="${keycmd#*:}"

		log 'Command %s\n' "$cmd"

		$cmd
		break
	done
}

####################
# Create and configure a special, never mapped, window 
# for Window Manager identification 
####################

create_wmcheck_window() {
	wmcheck_windowid=$(allocate_id)

	x_send_create_window $wmcheck_windowid 0 0 1 1 0 \
		$X_InputOnly $X_CopyFromParent $X_CopyFromParent
}

# Called by CreateNotify handler when wncheck_windowid is created
set_wmcheck_window_props() {
	local supported
	local root=${x_screen_0['root']}

	x_send_change_property $wmcheck_windowid $X_PropModeReplace \
		$XA_NET_SUPPORTING_WM_CHECK $XA_WINDOW 32 1 $wmcheck_windowid
	x_send_change_property $wmcheck_windowid $X_PropModeReplace \
		$XA_NET_WM_NAME $XA_UTF8_STRING 8 6 'bashwm'
	x_send_change_property $root $X_PropModeReplace \
		$XA_NET_SUPPORTING_WM_CHECK $XA_WINDOW 32 1 $wmcheck_windowid
	x_send_delete_property $root $XA_NET_CLIENT_LIST

	supported=( $XA_NET_CURRENT_DESKTOP $XA_NET_NUMBER_OF_DESKTOPS \
		$XA_NET_ACTIVE_WINDOW $XA_NET_SUPPORTED \
		$XA_NET_WM_STATE $XA_NET_SUPPORTING_WM_CHECK \
		$XA_NET_WM_STATE_FULLSCREEN $XA_NET_WM_WINDOW_TYPE \
		$XA_NET_WM_WINDOW_TYPE_DOCK $XA_NET_WM_WINDOW_TYPE_NORMAL \
		$XA_NET_CLIENT_LIST )

	x_send_change_property $root $X_PropModeReplace $XA_NET_SUPPORTED \
		$XA_ATOM 32 ${#supported[@]} ${supported[@]}
}


####################
# Adopt windows that existed before we started
####################

adopt_windows() {
	x_send_query_tree read_adopt_windows
}

read_adopt_windows() {
	local windowid 

	(( $# )) || return

	log 'Adopting %s windows\n' $#

	for windowid in "$@"; do
		log 'Checking prospective adoption of window %s\n' $windowid
		x_send_get_window_attributes $windowid check_window_attributes
	done

	x_when_sync update_workareas
}

check_window_attributes() {
	local windowid=$1
	local class=$2
	local map_state=$3
	local overide_redirect=$4

	if (( class == X_InputOnly || override_redirect )); then
		# We do not manage input only or override redirect windows
		# But createnotify does not tell us if input only
		# so we may have already created 'window_xxx' array
		[[ -v window_$windowid ]] && unset window_$windowid
		return
	fi

	# Windows we saw created will have x,y,etc
	# But adopted windows will not
	if [[ ! -v window_$windowid[x] ]]; then
		local mapped
		if (( map_state )); then
			mapped=$W_Mapped
		else
			mapped=$W_NotMapped
		fi
		declare -Ag "window_$windowid=( \
			mapped $mapped \
			take_focus 0 \
			delete_window 0 \
			)"		
		x_send_get_geometry $windowid read_adopt_window
	fi
}

read_adopt_window() {
	local windowid=$1
	local x=$2
	local y=$3
	local width=$4
	local height=$5
	local border_width=$6
	local -n window=window_$windowid

	window['x']=$x
	window['y']=$y
	window['width']=$width
	window['height']=$height
	window['border_width']=$border_width

	log 'Adopted %s\n' $windowid

	if (( window['mapped'] == $W_Mapped )); then
		pre_map $windowid adopt_window
	fi
}

adopt_window() {
	local windowid=$1
	local root=${x_screen_0['root']}
	local -n window=window_$windowid
	local monitorid
	local manage=1

	if [[ ${window[$XA_NET_WM_STRUT_PARTIAL]} ]]; then
		log 'Add strut %s\n' $windowid
		window['type']=strut
		monitorid=${ window_monitor $windowid; }
		log 'target monitor %d\n' $monitorid
		window['monitor']=$monitorid
		list_append monitor_$monitorid struts $windowid
		manage=0
	else
		window_config $windowid
		desktopid=${window['desktop']}
		case ${window['type']} in
			tile)
				list_push desktop_$desktopid tiles $windowid
				;;
			float)
				list_push desktop_$desktopid floats $windowid
				;;
		esac
	fi

	(( manage )) && clientlist_add $windowid
}

####################
# 
####################
handle_focus_in() {
	local windowid=$1
	local detail=$2
	local mode=$3

	(( mode == X_NotifyNormal || mode == X_NotifyWhileGrabbed )) || return
	
	(( x_screen_0['active'] != windowid )) || return

	local -n window=window_$windowid

	# Only interested if we manage the window and it is a mapped tile or float
	is_object window &&
		(( window['mapped'] == W_Mapped )) &&
		[[ ${window['type']} =~ tile|float ]] || return

	log 'FocusIn %s (%s %s)' $windowid $detail $mode

	focuslist_add $windowid
	set_active_window $windowid
}

set_border_color() {
	local windowid=$1
	local border_pixel=$2

	log 'Set border color for window %s to %s\n' $windowid $border_pixel

	x_send_change_window_attributes $windowid $X_CWBorderPixel $border_pixel
}

set_window_pos() {
	local windowid=$1
	local -n window=window_$windowid
	local x=${2:-${window['old_x']}}
	local y=${3:-${window['old_y']}}
	local width=${4:-${window['old_width']}}
	local height=${5:-${window['old_height']}}
	local border_width=${6:- \
			${window['old_border_width']:- \
			${window['border_width']}}}
	local stack_mode=$7
	local sibling=$X_None
	local length=8

	window['old_x']=${window['x']}
	window['old_y']=${window['y']}
	window['old_width']=${window['width']}
	window['old_height']=${window['height']}
	window['old_border_width']=${window['border_width']}

	window['x']=$x
	window['y']=$y
	window['width']=$width
	window['height']=$height

	# Don't let border width force window width or height < 1
	if (( width <= (2 * border_width) || height <= (2 * border_width) )); then
		border_width=0
	fi
	window['border_width']=$border_width

	mask=$(( X_CWX | X_CWY | X_CWWidth | X_CWHeight | X_CWBorderWidth ))

	if [[ $stack_mode ]]; then
		(( mask |= X_CWStackMode ))
	else
		stack_mode=$X_Above
	fi

	x_send_configure_window \
		$windowid $stack_mode $mask \
		$x $y $width $height $border_width $sibling
	
	x_send_synthetic_configure_notify $windowid $stack_mode $x $y \
		$width $height $border_width $sibling
}

set_wm_class() {
	local instance=$1
	local class=$2
	local len_instance=${#instance}
	local len_class=${#class}
	local bytes=()
	local i

	for (( i=0 ; i<len_instance ; i++ )); do
		bytes+=( "'${instance:i:1}" )
	done
	bytes+=( 0 )
	for (( i=0 ; i<len_class ; i++ )); do
		bytes+=( "'${class:i:1}" )
	done

	x_send_change_property ${x_screen_0['root']} $X_PropModeReplace \
		$XA_WM_CLASS $XA_STRING 8 ${#bytes[@]} "${bytes[@]}"
}

wm_protocols_changed() {
	local windowid=$1
	local -n window=window_$windowid
	local protocols=${window[$XA_WM_PROTOCOLS]}
	local protocol

	log 'Protocols changed for window %s to %s\n' $windowid "${protocols[*]}"

	for protocol in $protocols; do
		case $protocol in
			$XA_WM_TAKE_FOCUS)    window['take_focus']=1 ;;
			$XA_WM_DELETE_WINDOW) window['delete_window']=1 ;;
			*) ;;
		esac
	done
}

wm_hints_changed() {
	local windowid=$1
	local -n window=window_$windowid
	local hints=( ${window[$XA_WM_HINTS]} 1 1 )

	log 'Hints changed for window %s to %s\n' $windowid "${hints[*]}"

	window['input']=$(( hints[0] & 1 && hints[1] ))
}

set_property() {
	local windowid=$1
	local atom=$2
	local value=$3

	local -n window=window_$windowid
	window[$atom]=$3

	local handler="${wm_property_change_handlers[atom]}"

	log 'Window %s Property %d handled by %s\n' $windowid $atom $handler
	
	[[ $handler ]] && $handler $windowid $atom
}

update_workareas() {
	local m

	for m in "${wm_monitors[@]}"; do
		calculate_workarea $m
	done
	update_net_workarea
}


is_fixed_size() {
	local hints=${1:-'0 0 0 0 0'}

	# hints[0] = flags
	# hint[1 2] = minimum width height
	# hint[3 4] = maximum width height
	(( hints[0] & X_WM_PMinSize && 
		hints[0] & X_WM_PMaxSize &&
		hints[1] == hints[3] && 
		hints[2] == hints[4] ))
}

is_normal_type() {
	local net_type=${1:-$XA_NET_WM_WINDOW_TYPE_NORMAL}
	[[ $net_type == $XA_NET_WM_WINDOW_TYPE_NORMAL ]]
}

window_config() {
	local windowid=$1
	local -n window=window_$windowid
	local border_width=$wm_border_width

	window['desktop']=${window['desktop']:-$wm_current_desktop}

	if [[ -z ${window['type']} ]]; then	
		if [[ ${window[$XA_WM_TRANSIENT_FOR]} == 1 ]] ||
				is_fixed_size ${window[$XA_WM_NORMAL_HINTS]} ||
				! is_normal_type ${window[$XA_NET_WM_WINDOW_TYPE]}; then
			window['type']=float
		else
			window['type']=tile
		fi
	fi

	if ! is_fixed_size ${window[$XA_WM_NORMAL_HINTS]}; then
		window['border_width']=$wm_border_width
	fi
}

allocate_id() {
	if (( last_id )); then
		(( last_id++ ))
	else
		last_id=1
		while (( ! last_id & ${x_server['resource_id_mask']} )); do
			(( last_id <<= 1))
		done
	fi

	echo $(( ${x_server['resource_id_base']} | last_id ))
}

request_get_monitors() {
	(( getmonitors )) && return
	getmonitors=1
	x_when_idle process_get_monitors
}

process_get_monitors() {
	(( getmonitors )) || return
	getmonitors=0
	x_send_rr_get_monitors check_update_monitors
	return
}

check_update_monitors() {
	# If another request_get_monitors has run then discard this reply
	(( getmonitors == 0 )) && update_monitors "$@"
}


update_monitors() {
	local name m monitorid name_atom
	local prev_monitors=" ${wm_monitors[*]} "
	wm_monitors=()
	unset 'x_screen_0['primary']'

	log 'Update wm_monitors nmonitors=%d\n' $#
	for m in "$@"; do
		m=( $m )
		name_atom=${m[0]}
		monitorid=$name_atom

		name=${xa_names[name_atom]}
		[[ $name ]] || x_send_get_atom_name $name_atom set_atom_name

		(( primary )) && x_screen_0['primary']=$monitorid

		monitor_config "${m[@]}"

		wm_monitors+=( $monitorid )
		prev_monitors=${prev_monitors/ $monitorid / }
	done

	x_screen_0['primary']=${x_screen_0['primary']:-${wm_monitors[0]}}

	for m in $prev_monitors; do
		monitor_remove $m
	done

	desktop_monitor_config

	update_workareas 

	for m in "${wm_monitors[@]}"; do
		layout_monitor $m
	done

	update_net_viewport

	x_when_sync monitors_update_notify
}

handle_error() {
	local code=$1
	local data=$2
	local major_op_code=$3
	local minor_op_code=$4

	local res=$code

	case $code in
		$X_BadWindow) res=0
			;;
		$X_BadMatch)
			if (( major_op_code == X_SetInputFocus ||
				major_op_code == X_ConfigureWindow )); then
				res=0
			fi
			;;
		$X_BadAccess)
			if (( major_op_code == X_GrabButton ||
				major_op_code == X_GrabKey )); then
				res=0
			fi
			;;
		0)	# something very wrong
			res=255
			;;
	esac

	if (( $res )); then
		log 'Error code: %d\n' $code
		log 'Error data: %04x\n' $data
		log 'Error op code: %d:%d\n' $major_op_code $minor_op_code

		x_exit $res
	fi
}

handle_create_notify() {
	local windowid=$1
	local x=$2
	local y=$3
	local width=$4
	local height=$5
	local border_width=$6
	local override_redirect=$7

	(( override_redirect )) && return

	log 'Process CreateNotify Event %s\n' $windowid

	if [[ $windowid == $wmcheck_windowid ]]; then
		set_wmcheck_window_props
		return
	fi

	declare -Ag "window_$windowid=( \
		x $x \
		y $y \
		width $width \
		height $height \
		border_width $border_width \
		mapped $W_NotMapped \
		take_focus 0 \
		delete_window 0 \
		)"
	
	log_array window_$windowid

	x_send_get_window_attributes $windowid check_window_attributes
}

handle_configure_request() {
	local windowid=$1
	local stack_mode=$2
	local value_mask=$3
	local x=$4
	local y=$5
	local width=$6
	local height=$7
	local border_width=$8
	local sibling=$9

	log 'Process ConfigureRequest Event %s\n' $windowid

	local -n window=window_$windowid
	if is_object window; then
		log_array window_$windowid
		(( $value_mask & $X_CWX )) && window['x']=$x
		(( $value_mask & $X_CWY )) && window['y']=$y
		(( $value_mask & $X_CWWidth )) && window['width']=$width
		(( $value_mask & $X_CWHeight )) && window['height']=$height
		(( $value_mask & $X_CWBorderWidth )) && window['border_width']=$border_width
		log_array window_$windowid
	fi

	# Configure requested window, even if we are not managing it
	x_send_configure_window "$@"
	
	x_send_synthetic_configure_notify $windowid $stack_mode ${window['x']} \
		${window['y']} ${window['width']} ${window['height']} \
		${window['border_width']} $sibling
}

handle_property_notify() {
	local windowid=$1
	local atom=$2
	local state=$3

	log '< PropertyNotify for window %s, %s, state %s\n' \
		$windowid ${ xa_name $atom; } $state
}

handle_enter_notify() {
	local windowid=$1
	local timestamp=$2
	local detail=$3
	local mode=$4
	local flags=$5

	(( mode == X_NotifyNormal )) || return

	# Non-root window wanted but only if 
	# enter was not from child to parent and was triggered by motion 
	if (( $windowid != ${x_screen_0['root']} &&
			( detail == X_NotifyInferior || 
			  mode != X_NotifyNormal ) )); then
		return
	fi

	is_object window_$windowid || return

	log 'Process EnterNotify on window %s detail %s mode %s flags %s\n' \
		$windowid $detail $mode $flags

	# Make sure it is one of our tile/float windows
	local -n window=window_$windowid

	case ${window['type']} in
		tile|float)
			focuslist_add $windowid
			setfocus $windowid $timestamp
			;;
		*)
			setfocus 0 $timestamp
			;;
	esac
}

handle_destroy_notify() {
	local windowid=$1
	local event=$2
	local window

	(( event == ${x_screen_0['root']} )) || return

	is_object window_$windowid || return

	log 'DestroyWindow %s' $windowid

	remove_window $windowid
}

handle_unmap_notify() {
	local windowid=$1
	local event=$2

	local root=${x_screen_0['root']}

	(( event == root )) || return

	local -n window=window_$windowid
	is_object window || return

	# We may have already handled the unmapping
	(( window['mapped'] == $W_Mapped )) || return

	log 'UnmapNotify %s' $windowid

	remove_window $windowid
}

handle_map_request() {
	local windowid=$1

	log 'MapRequest %s' $windowid

	# Pass on the map request if we are not managing window
	if ! is_object window_$windowid; then
		x_send_map_window $windowid
		return
	fi

	local -n window=window_$windowid
	if (( window['mapped'] == W_NotMapped )); then
		window['mapped']=$W_MapRequested
		pre_map $windowid map_window
	elif (( window['mapped'] == W_Unmapped )); then
		map_window $windowid
	fi
}

add_tile() {
	local windowid=$1
	local -n window=window_$windowid
	local desktopid=${window['desktop']}

	list_push desktop_$desktopid tiles $windowid
}

add_float() {
	local windowid=$1
	local -n window=window_$windowid
	local desktopid=${window['desktop']}
	
	list_push desktop_$desktopid floats $windowid
}

layout_desktop() {
	local desktopid=$1
	local force=${2:-0}

	local -n desktop=desktop_$desktopid

	log 'layout_desktop: desktop=%s force=%s\n' $desktopid $force 

	log ' :dirty=%s\n' ${desktop['dirty']}

	(( force || desktop['dirty'] )) || return

	log ' :laying out windows\n'

	layout_tiles $desktopid
	layout_floats $desktopid

	desktop['dirty']=0
}

layout_tiles() {
	local desktopid=$1
	local -n desktop=desktop_$desktopid
	local tiles=( ${desktop['tiles']} )
	local monitorid=${wm_desktop_monitor[desktopid]}
	local -n monitor=monitor_$monitorid

	local num_tiles=${#tiles[@]}
	local x=$(( monitor['x'] + monitor['wa_x'] ))
	local y=$(( monitor['y'] + monitor['wa_y'] ))
	local width=${monitor['wa_width']}
	local height=${monitor['wa_height']}
	local window w h hdiff i

	log 'Laying out %d tiles for desktop %d on monitor %d\n' \
		$num_tiles $desktopid $monitorid

	case $num_tiles in
		0)	:
			;;
		1)	set_window_pos ${tiles[0]} \
				$x $y $width $height
			;;
		2)	w=$(( width / 2 ))
			set_window_pos ${tiles[0]} \
				$x $y $w $height
			set_window_pos ${tiles[1]} \
				$((x + w)) $y $((width - w)) $height
			;;
		*)      w=$(( width / 2))
			set_window_pos ${tiles[0]} \
				$x $y $w $height
			(( x+=w, width-=w ))
			h=$(( height / (num_tiles - 1) ))
			hdiff=$(( height - (h * (num_tiles - 1)) ))
			for (( i=1 ; i<num_tiles ; i++ )); do
				set_window_pos ${tiles[i]} \
					$x $y \
					$width $(( h + hdiff ))
				(( y += h + hdiff, hdiff = 0 ))
			done
			;;
	esac
}

# This is broken as floats need to know where they were relative to
# previous work area, and that info is not available here
# For now just make sure all are visible
layout_floats() {
	local desktopid=$1
	local -n desktop=desktop_$desktopid
	local floats=( ${desktop['floats']} )

	local -n monitor=monitor_${wm_desktop_monitor[desktopid]}

	local x=$(( monitor['x'] + monitor['wa_x'] ))
	local y=$(( monitor['y'] + monitor['wa_y'] ))
	local width=${monitor['wa_width']}
	local height=${monitor['wa_height']}

	local window i

	log 'Laying out %d floats\n' ${#floats[@]}

	for f in "${floats[@]}"; do
		log 'Laying out float %s in work area x=%d y=%d width=%d height=%d\n' \
			$f $x $y $width $height

		log_array window_$f

		local -n window=window_$f

		if (( window['width'] >= width )); then
			window['x']=$x
			window['width']=$width
		elif (( window['x'] < x || window['x'] + window['width'] > x + width )); then
			window['x']=$(( x + (width - window['width'])/2 ))
		fi

		if (( window['height'] >= height )); then
			window['y']=$y
			window['height']=$height
		elif (( window['y'] < y || window['y'] +window['height'] > y + height )); then
			window['y']=$(( y + (height - window['height'])/2 ))
		fi

		set_window_pos $f ${window['x']} ${window['y']} \
				${window['width']} ${window['height']}

		log_array window_$f
	done
}

get_property() {
	local windowid=$1
	local atom=$2
	local atom_type=$3
	local length=$4

	x_send_get_property $windowid $atom $atom_type $length set_property
}

pre_map() {
	local windowid=$1
	local next_handler=$2

	get_property $windowid $XA_WM_PROTOCOLS $XA_ATOM 6
	get_property $windowid $XA_WM_NAME $XA_STRING 20
	get_property $windowid $XA_WM_CLASS $XA_STRING 20
	get_property $windowid $XA_NET_WM_WINDOW_TYPE $XA_ATOM 1
	get_property $windowid $XA_NET_WM_STRUT_PARTIAL $XA_CARDINAL 12
	get_property $windowid $XA_WM_TRANSIENT_FOR $XA_WINDOW 1
	get_property $windowid $XA_WM_NORMAL_HINTS $XA_WM_SIZE_HINTS 18
	get_property $windowid $XA_WM_HINTS $XA_WM_HINTS 9

	x_when_server_sync pre_map_customize $windowid $next_handler

	change_window_events $windowid $wm_client_events
}

pre_map_customize() {
	local windowid=$1
	local handler=$2

	custom_pre_map $windowid && $handler $windowid
}

# Called just before window is mapped for the first time
custom_pre_map() {
	local windowid=$1

	# Example: make Gimp windows float (default is tile)
	#
	# local -n window=window_$windowid
	# local wm_class=( ${window[$XA_WM_CLASS]} )
	# # wm_class = ( 'instance' 'class' )
	# [[ ${wm_class[1]} =~ Gimp ]] && window['type']=float
	#
	# # 0 - map window, other - do not map window
	# return 0
}

max() {
	(( $1 > $2 )) && echo $1 && return
	echo $2
}

min() {
	(( $1 < $2 )) && echo $1 && return
	echo $2
}

calculate_workarea() {
	local monitorid=$1
	log 'Calculate work area for monitor %s\n' $monitorid

	local -n monitor=monitor_$monitorid

	is_object monitor || die 'No such monitor %s\n' $monitorid

	local left=0
	local right=0
	local top=0
	local bottom=0
	local x=0
	local y=0
	local width=${monitor['width']}
	local height=${monitor['height']}
	local wa_x=${monitor['wa_x']:-0}
	local wa_y=${monitor['wa_y']:-0}
	local wa_width=${monitor['wa_width']:-0}
	local wa_height=${monitor['wa_height']:-0}
	local root=${x_screen_0['root']}
	local id window strut sstrut
	
	log 'Struts: %s\n' "${monitor['struts']}"

	for id in ${monitor['struts']}; do
		log_array window_$id
		local -n window=window_$id
		sstrut="${window[$XA_NET_WM_STRUT_PARTIAL]}"
		log 'Strut: %s\n' "$sstrut"
		strut=( $sstrut )
		(( ${#strut[@]} >= 4 )) || continue
		left=${ max $left ${strut[0]}; }
		right=${ max $right ${strut[1]}; }
		top=${ max $top ${strut[2]}; }
		bottom=${ max $bottom ${strut[3]}; }
	done
	x=$left
	y=$top
	(( width -= left + right ))
	(( height -= top + bottom ))
	
	if (( monitor['wa_x'] == x &&
			monitor['wa_y'] == y &&
			monitor['wa_width'] == width && 
			monitor['wa_height'] == height )); then
		return
	fi

	log 'Work Area for Monitor %s: x=%s y=%s width=%s height=%s\n' \
		$monitorid $x $y $width $height

	monitor['wa_x']=$x
	monitor['wa_y']=$y
	monitor['wa_width']=$width
	monitor['wa_height']=$height

	desktop_dirty ${monitor['desktops']}

}

desktop_dirty() {
	local d

	for d in "$@"; do
		log 'desktop_dirty: <%s>\n' $d
		local -n desktop=desktop_$d
		desktop['dirty']=1
	done
}

update_net_workarea() {
	local vals=()
	local i
	for (( i=0 ; i<wm_desktop_count ; i++ )); do
		local -n monitor=monitor_${wm_desktop_monitor[i]}
		vals+=( ${monitor['wa_x']} \
			${monitor['wa_y']} \
			${monitor['wa_width']} \
			${monitor['wa_height']} )
	done

	[[ ${vals[*]} != ${wm_properties['workarea']} ]] || return

	wm_properties['workarea']=${vals[*]}

	log 'Work area values %s\n' "$wm_properties['workarea']"

	x_send_change_property ${x_screen_0['root']} $X_PropModeReplace \
		$XA_NET_WORKAREA $XA_CARDINAL 32 ${#vals[@]} "${vals[@]}"
}

setlastfocus() {
	local -n focuslist=focuslist_$wm_current_desktop

	setfocus ${focuslist[@]: -1}
}

setfocus() {
	local windowid=$1
	local timestamp=${2:-$X_CurrentTime}

	if (( $windowid )); then
		local -n window=window_$windowid

		log 'Set Focus for window %s\n' $windowid

		log 'Window %s[mapped] = %s\n' $windowid ${window['mapped']} 

		(( window['mapped'] == $W_Mapped )) || return

		if (( window['take_focus'] )); then
			x_send_protocol_message $windowid $XA_WM_TAKE_FOCUS
		else
			x_send_set_input_focus $windowid $timestamp
		fi
	else
		log 'Set focus to PointerRoot\n'

		set_active_window 0
		x_send_set_input_focus $X_PointerRoot $timestamp
	fi
}

set_active_window() {
	local windowid=$1
	local active_window=${x_screen_0['active']:-0}

	log 'SetActiveWindow <%s> -> <%s>\n' "$active_window" "$windowid"

	(( $windowid != $active_window )) || return

	if (( active_window )); then
		local -n window=window_$active_window
		if is_object window; then
			set_border_color $active_window $wm_border_inactive
		fi
	fi

	active_window=$windowid

	x_screen_0['active']=$active_window
	if (( active_window )); then
		local -n window=window_$active_window
		set_border_color $active_window $wm_border_active
		x_send_change_property ${x_screen_0['root']} $X_PropModeReplace \
			$XA_NET_ACTIVE_WINDOW $XA_WINDOW 32 1 $active_window
		set_current_desktop ${window['desktop']}
	else
		x_send_delete_property ${x_screen_0['root']} $XA_NET_ACTIVE_WINDOW
	fi
}

set_current_desktop() {
	desktopid=$1

	(( desktopid != wm_current_desktop )) || return

	log 'SetCurrentDesktop <%s> -> <%s>\n' $wm_current_desktop $desktopid

	wm_current_desktop=$desktopid

	x_send_change_property ${x_screen_0['root']} $X_PropModeReplace \
		$XA_NET_CURRENT_DESKTOP $XA_CARDINAL 32 1 $wm_current_desktop
}

focuslist_add() {
	local windowid=$1
	local -n window=window_$windowid
	local desktopid=${window['desktop']}
	local -n focuslist=focuslist_$desktopid


	remove_id focuslist $windowid

	log 'Adding window %s to focus list for desktop %s\n' $windowid $desktopid

	focuslist+=( $windowid )
}

focuslist_remove() {
	local windowid=$1
	local -n window=window_$windowid
	local desktopid=${window['desktop']}
	local -n focuslist=focuslist_$desktopid

	log 'Removing window %s from focus list for desktop %s\n' $windowid $desktopid

	remove_id focuslist $windowid
}

calc_overlap() {
	local monitorid=$1
	local windowid=$2
	local -n m=monitor_$monitorid
	local -n w=window_$windowid

	local tx=${ max ${m[x]} ${w[x]}; }
	local ty=${ max ${m[y]} ${w[y]}; }
	local bx=${ min $((m[x] + m[width])) $((w[x] + w[width])); }
	local by=${ min $((m[y] + m[height])) $((w[y] + w[height])); }

	log 'Calc Overlap top-left(%d:%d) bottom-right(%d:%d)\n' \
		$tx $ty $bx $by

	if (( tx >= bx || ty >= by )); then
		echo 0
	else
		echo $(( (bx - tx) * (by - ty) ))
	fi
}

window_monitor() {
	local windowid=$1
	local max_overlap=0
	local overlap m
	local monitorid=${x_screen_0['primary']}

	log 'Find monitor for window %d, checking %d wm_monitors\n' $windowid ${#wm_monitors[@]}

	for m in "${wm_monitors[@]}"; do
		overlap=${ calc_overlap $m $windowid; }
		log 'Window %d -> Monitor %d Overlap=%d\n' $windowid $m $overlap
		if (( overlap > max_overlap )); then
			max_overlap=overlap
			monitorid=$m
		fi
	done
	echo $monitorid
}
	
map_window() {
	local windowid=$1
	local root=${x_screen_0['root']}
	local -n window=window_$windowid
	local monitorid desktopid
	local manage=1

	log_array window

	(( window['mapped'] != W_Mapped )) || return

	if [[ ${window[$XA_NET_WM_STRUT_PARTIAL]} ]]; then
		log 'Add strut %s\n' $windowid
		window['type']=strut
		monitorid=${ window_monitor $windowid; }
		log 'target monitor %d\n' $monitorid
		window['monitor']=$monitorid
		list_append monitor_$monitorid struts $windowid
		calculate_workarea $monitorid
		layout_monitor $monitorid
		update_net_workarea
		manage=0
	else
		window_config $windowid
		desktopid=${window['desktop']}
		case ${window['type']} in
			tile)
				log 'Add tile %s\n' $windowid
				list_push desktop_$desktopid tiles $windowid
				layout_tiles $desktopid
				;;
			float)
				log 'Add float %s\n' $windowid
				list_push desktop_$desktopid floats $windowid
				layout_floats $desktopid
				;;
		esac
	fi
	
	is_object window && window['mapped']=$W_Mapped

	x_send_map_window $windowid

	(( manage )) || return

	clientlist_add $windowid

	if (( window['input'] )); then
		focuslist_add $windowid
		setfocus $windowid
	fi
}

add_desktop_window() {
	local desktopid=$1
	local windowid=$2
	local -n window=window_$windowid

	window['desktop']=$desktopid
	case ${window['type']} in
		tile)
			list_push desktop_$desktopid tiles $windowid
			;;
		float)
			list_push desktop_$desktopid floats $windowid
			;;
	esac

	desktop_dirty $desktopid

	if (( window['input'] )); then
		focuslist_add $windowid
	fi
}

remove_desktop_window() {
	local windowid=$1
	local unmapped=$2
	local -n window=window_$windowid

	local desktopid=${window['desktop']}
	[[ $desktopid ]] || return

	local monitorid=${wm_desktop_monitor[desktopid]}
	local type=${window['type']}

	log 'Remove %s window %s from desktop %s\n' $type $windowid $desktopid

	case $type in
		tile)   
			list_remove desktop_$desktopid tiles $windowid
			desktop_dirty $desktopid
			;;
		float) 
			list_remove desktop_$desktopid floats $windowid
			desktop_dirty $desktopid
			;;
	esac

	if (( window['input'] )); then
		log 'Remove window %s from focuslist (active=%s)\n' \
			$windowid ${x_screen_0['active']}

		focuslist_remove $windowid
	fi

	if (( unmapped )); then
		window['mapped']=$W_Unmapped
	fi
	unset 'window[desktop]'
}

is_object() {
	local -n _o=$1
	[[ ${_o@a} == A ]]
}

remove_window() {
	local windowid=$1
	local desktopid

	local -n window=window_$windowid

	case ${window['type']} in
		strut)
			monitorid=${window['monitor']}
			local -n monitor=monitor_$monitorid
			if is_object monitor; then
				list_remove monitor struts $windowid
				calculate_workarea $monitorid
				layout_monitor $monitorid
				update_net_workarea
			fi
			;;
		tile|float)
			desktopid=${window['desktop']}
			if [[ -z $desktopid ]]; then
				log 'Removing window %s without desktop\n' $windowid
				log_array window
				return
			fi
			remove_desktop_window $windowid 0
			layout_desktop $desktopid
			clientlist_remove $windowid
			;;
	esac

	unset 'window'
}

remove_id() {
	local arr=$1
	local -n ids=$arr
	local id=$2
	local list=" ${ids[*]} "

	log 'Removing %s from %s\n' $id "$arr"

	ids=( ${list/ $id / } )

	log 'Remove <%s> from <%s> => (%s)\n' "$id" "$list" "${ids[*]}"
}

clientlist_add() {
	local windowid=$1

	[[ $clientlist =~ " $windowid " ]] && return

	clientlist+=( $windowid )

	send_clientlist_append $windowid
}

clientlist_remove() {
	local windowid=$1

	[[ $clientlist =~ " $windowid " ]] || return

	remove_id clientlist $windowid

	send_clientlist_update
}

send_clientlist_append() {
	local windowid=$1
	local root=${x_screen_0['root']}

	x_send_change_property $root $X_PropModeAppend $XA_NET_CLIENT_LIST \
		$XA_WINDOW 32 1 $windowid
}

send_clientlist_update() {
	local root=${x_screen_0['root']}

	if (( ${#clientlist[@]} )); then
		x_send_change_property $root $X_PropModeReplace \
			$XA_NET_CLIENT_LIST $XA_WINDOW 32 \
			${#clientlist[@]} ${clientlist[@]}
	else
		x_send_delete_property $root $XA_NET_CLIENT_LIST
	fi
}


change_window_state() {
	local windowid=$1
	local prop=$2
	local action=${3:-$X_NET_WM_StateToggle}
	local is_present if_present if_absent

	local -n window=window_$windowid
	local state=${window['state']:-' '}

	log 'Change window %s state from (%s) with property %s, action %s\n' \
		$windowid "$state" ${ xa_name prop; } $action 

	case $action in
		$X_NET_WM_StateRemove ) if_present=1  ;;
		$X_NET_WM_StateAdd )    if_absent=1   ;;
		$X_NET_WM_StateToggle ) if_present=1; if_absent=1 ;;
		* ) fail "Invalid change_window_state action %s\n" $action
	esac
	
	[[ $state =~ " $prop " ]] && is_present=1
	(( if_present && is_present )) && state="${state/$prop / }"
	(( if_absent && ! is_present )) && state+="$prop "
	
	window['state']=$state

	log 'Window %s state changed to (%s)\n' $windowid "$state"
}

update_window_state() {
	local windowid=$1
	local action=$2
	shift 2
	local prop

	for prop in "$@"; do
		(( prop == XA_NET_WM_STATE_FULLSCREEN )) || continue
		change_window_state $windowid $prop $action
	done
}

update_fullscreen() {
	local windowid=$1
	local is_fullscreen
	local want_fullscreen=0
	local fs_prop=$XA_NET_WM_STATE_FULLSCREEN
	local -n window=window_$windowid

	is_fullscreen=$(( window['fullscreen'] ))
	[[ ${window['state']} =~ " $fs_prop " ]] && want_fullscreen=1

	if (( ! is_fullscreen && want_fullscreen )); then
		local -n monitor=monitor_${wm_desktop_monitor[window['desktop']]}
		set_window_pos $windowid \
			${monitor['x']} ${monitor['y']} \
			${monitor['width']} ${monitor['height']} \
			0 $X_Above
		window['fullscreen']=1
		x_send_change_property $windowid $X_PropModeReplace \
			$XA_NET_WM_STATE $XA_ATOM 32 1 $XA_NET_WM_STATE_FULLSCREEN
	elif (( is_fullscreen && ! want_fullscreen )); then
		set_window_pos $windowid
		window['fullscreen']=0
		x_send_delete_property $windowid $XA_NET_WM_STATE
	fi
}

handle_client_message() {
	local windowid=$1
	local atom=$2
	shift 2

	log 'ClientMessage %s %s [%s]\n' \
			$windowid ${ xa_name $atom; } "$*"

	case $atom in
	$XA_NET_CURRENT_DESKTOP) 
		select_desktop $1 
		;;
	$XA_NET_WM_STATE)
		is_object window_$windowid || return
		update_window_state $windowid $1 $2 $3
		update_fullscreen $windowid
		;;
	esac
}



select_desktop() {
	local desktopid=$1
	local top_desktop=$wm_current_desktop

	log 'Selecting desktop %d, current %d\n' $desktopid $wm_current_desktop

	(( wm_current_desktop != desktopid )) || return

	local current_monitor=${wm_desktop_monitor[wm_current_desktop]}
	local monitorid=${wm_desktop_monitor[desktopid]}

	log 'Selecting monitor %d, current %d\n' $monitorid $current_monitor

	local -n monitor=monitor_$monitorid

	if (( current_monitor != monitorid )); then
		top_desktop=${ list_head monitor desktops; }
	fi

	if (( top_desktop == desktopid )); then
		set_current_desktop $top_desktop
		setlastfocus
	else
		hide_desktop $top_desktop
		set_current_desktop $desktopid
		show_desktop $wm_current_desktop
		list_push monitor desktops $wm_current_desktop
	fi
}

hide_desktop() {
	local desktopid=$1
	local -n desktop=desktop_$desktopid
	local windows=( ${desktop['tiles']} ${desktop['floats']} )
	local active=${x_screen_0['active']}
	local id

	log 'Hide Desktop %s\n' $desktopid
	log 'Unmapping %s windows\n' ${#windows[@]}
	for id in ${windows[@]}; do
		local -n window=window_$id

		if (( id == active )); then
			set_active_window 0
			x_send_set_input_focus $X_None $X_CurrentTime
			x_send_unmap_window $id
			x_send_set_input_focus $X_PointerRoot $X_CurrentTime
		else
			x_send_unmap_window $id
		fi

		window['mapped']=$W_Unmapped
	done
}

show_desktop() {
	local desktopid=$1
	local -n desktop=desktop_$desktopid
	local windows=( ${desktop['tiles']} ${desktop['floats']} )
	local id

	log 'Show Desktop %s\n' $desktopid
	layout_desktop $desktopid
	log 'Mapping %s windows\n' ${#windows[@]}
	for id in ${windows[@]}; do
		local -n window=window_$id
		window['mapped']=$W_Mapped
		x_send_map_window $id
	done
	setlastfocus
}

move_to_desktop() {
	local desktopid=$1
	local dtop

	log 'Move window to desktop %d, current %d\n' $desktopid $wm_current_desktop

	(( wm_current_desktop != desktopid )) || return

	local current_monitor=${wm_desktop_monitor[wm_current_desktop]}
	local monitorid=${wm_desktop_monitor[desktopid]}

	log 'New monitor %d, current %d\n' $monitorid $current_monitor

	local windowid=${x_screen_0['active']}

	[[ $windowid ]] || return

	local -n window=window_$windowid

	[[ ${window['desktop']} == $wm_current_desktop && 
		${window['type']} =~ tile|float ]] || return

	dtop=${ list_head monitor_$monitorid desktops; }

	if (( desktopid != dtop )); then	
		remove_desktop_window $windowid 1
		if (( windowid == ${x_screen_0['active']} )); then
			local -n focuslist=focuslist_$wm_current_desktop
			if (( ${#focuslist[@]} )); then
				setlastfocus
				x_send_unmap_window $windowid
			else
				set_active_window 0
				x_send_set_input_focus $X_None $X_CurrentTime
				x_send_unmap_window $windowid
				x_send_set_input_focus $X_PointerRoot $X_CurrentTime
			fi
		else
			x_send_unmap_window $windowid
		fi
		window['mapped']=$W_Unmapped
	else
		remove_desktop_window $windowid 0
	fi
	add_desktop_window $desktopid $windowid

	layout_desktop $wm_current_desktop
	if (( window['mapped'] )); then
		layout_desktop $desktopid
	fi
}

change_window_events() {
	local windowid=$1
	local event_mask=$2

	x_send_change_window_attributes $windowid $X_CWEventMask $event_mask
}

delete_window() {
	local windowid=${x_screen_0['active']}
	(( $windowid )) || return
	local -n window=window_$windowid

	log 'Delete window %s\n' $windowid

	if (( window['delete_window'] )); then
		log 'Using delete_window protocol\n'

		x_send_protocol_message $windowid $XA_WM_DELETE_WINDOW
	else
		log 'Sending DestroyWindow op code\n'

		x_send_destroy_window $windowid
	fi
}

list_head() {
	local -n array=$1
	local index=$2
	local list=${array[$index]:1}
	echo ${list%% *}
	echo $head
}

list_remove() {
	local -n array=$1
	local index=$2
	local item=$3
	local list=${array[$index]}
	array[$index]="${list/ $item / }"
}

list_pop() {
	local -n array=$1
	local index=$2
	local list=${array[$index]:1}
	local head=${list%% *}
	array[$index]=${list:${#head}}
	echo $head
}


list_push() {
	local -n array=$1
	local index=$2
	local item=$3
	local list=${array[$index]:-' '}
	array[$index]=" ${item}${list/ $item / }"
}

list_append() {
	local -n array=$1
	local index=$2
	local list=${array[$index]:-' '}
	shift 2
	local item
	for item in "$@"; do
		list="${list/ $item / }${item} "
	done
	array[$index]="$list"
}

desktop_to_monitor() {
	local monitorpos=$1

	(( monitorpos < ${#wm_monitors[@]} )) || return

	local to_monitorid=${wm_monitors[monitorpos]}
	local from_monitorid=${wm_desktop_monitor[wm_current_desktop]}

	(( to_monitorid != from_monitorid )) || return

	log 'Setting wm_desktop_monitor[%d]=%d\n' $wm_current_desktop $to_monitorid

	wm_desktop_monitor[wm_current_desktop]=$to_monitorid

	local -n monitor=monitor_$from_monitorid
	log 'Remove desktop %d from monitor_%d[desktops](%s)\n' $wm_current_desktop $from_monitorid "${monitor['desktops']}"
	list_remove monitor desktops $wm_current_desktop
	desktopid=${ list_head monitor desktops; }
	log 'Got first desktop %s from monitor_%d[desktops](%s)\n' ${desktopid:-<none>} $from_monitorid "${monitor['desktops']}"
	[[ $desktopid ]] && show_desktop $desktopid

	local -n monitor=monitor_$to_monitorid
	local desktopid=${ list_head monitor desktops; }
	log 'Got first desktop %s from monitor_%d[desktops](%s)\n' ${desktopid:-<none>} $to_monitorid "${monitor['desktops']}"
	[[ $desktopid ]] && hide_desktop $desktopid
	list_push monitor desktops $wm_current_desktop
	log 'Added desktop %d to monitor_%d[desktops](%s)\n' $wm_current_desktop $to_monitorid "${monitor['desktops']}"

	layout_desktop $wm_current_desktop 1

	setlastfocus

	update_net_workarea
	update_net_viewport
}

swap_master() {
	local active=${x_screen_0['active']}

	[[ $active ]] || return

	local -n window=window_$active

	[[ ${window[type]} == tile ]] || return

	local -n desktop=desktop_$wm_current_desktop

	if [[ $active == ${ list_head desktop tiles; } ]]; then
		local master=${ list_pop desktop tiles; }
		local next=${ list_pop desktop tiles; }
		list_push desktop tiles $master
		[[ $next ]] && list_push desktop tiles $next
	else
		list_push desktop tiles $active
	fi
	layout_desktop $wm_current_desktop 1
}


wm_exit() {
	exit
}

spawn() {
	/usr/bin/env --default-signal -C "$HOME" setsid -f "$@" &>> $logfile
}

new_terminal() {
	spawn terminal
}

new_browser() {
	spawn browser
}

show_menu() {
	spawn dmenu_run
}

register_property_handlers() {
	wm_property_change_handlers[XA_WM_HINTS]=wm_hints_changed
}


#
# override in config.sh to update status bar(s) after monitor change
monitors_update_notify() {
	: 
}

update_net_viewport() {
	local i
	local vals=()

	for (( i=0 ; i<wm_desktop_count ; i++ )); do
		local -n monitor=monitor_${wm_desktop_monitor[i]}
		vals+=( ${monitor['x']} ${monitor['y']} )
	done

	[[ ${vals[*]} != ${wm_properties['viewport']} ]] || return

	wm_properties['viewport']=${vals[*]}

	x_send_change_property ${x_screen_0['root']} $X_PropModeReplace \
		$XA_NET_DESKTOP_VIEWPORT $XA_CARDINAL 32 ${#vals[@]} "${vals[@]}"
}

monitor_remove() {
	local monitorid=$1
	local -n monitor=monitor_$monitorid
	local struts=${monitor['struts']}
	local desktops=${monitor['desktops']}
	local primary=${x_screen_0['primary']}
	local s d

	for s in $struts; do
		unset 'window_$s'
	done

	for d in $desktops; do
		log 'Setting wm_desktop_monitor[%s]=%s\n' $d $primary
		wm_desktop_monitor[d]=$primary
	done

	list_append monitor_$primary desktops $desktops
	desktop_dirty $desktops

	local rtop=${ list_head monitor_$monitorid desktops; }
	local ptop=${ list_head monitor_$primary desktops; }

	if [[ $rtop ]]; then
		if (( $rtop == $ptop )); then
			layout_desktop $rtop
			setlastfocus
		else
			hide_desktop $rtop
		fi
	fi

	unset 'monitor'
}

default_monitor_config() {
	monitor_config 0 1 1 0 0 \
		${x_screen_0['width_pixels']} ${x_screen_0['height_pixels']}
}

monitor_config() {
	local monitorid=$1
	local primary=$2
	local auto=$3
	local x=$4
	local y=$5
	local width=$6
	local height=$7
	#local width_mm=$8
	#local height_mm=$9

	log 'Monitor id=%s primary=%s auto=%s x=%s y=%s width=%s height=%s\n' \
		$1 $2 $3 $4 $5 $6 $7

	local -n monitor=monitor_$monitorid

	if ! is_object monitor; then
		log 'Declaring monitor_%s\n' $monitorid
		declare -Ag "monitor_$monitorid=( \
			wa_x 0 \
			wa_y 0 \
			wa_width $width \
			wa_height $height \
			desktops ' ' \
			struts ' ' \
			)"
		local -n monitor=monitor_$monitorid
	fi
	monitor['name_atom']=$monitorid
	monitor['primary']=$primary
	monitor['auto']=$auto
	monitor['x']=$x
	monitor['y']=$y
	monitor['width']=$width
	monitor['height']=$height
	shift 9
	monitor['outputs']=$*
}

layout_monitor() {
	local monitorid=$1

	log 'Layout monitor %d\n' $monitorid
	local desktopid=${ list_head monitor_$monitorid desktops; }
	[[ $desktopid ]] && layout_desktop $desktopid
}

desktop_monitor_config() {
	local d
	local primary=${x_screen_0['primary']}

	if (( ${#wm_desktop_monitor} == 0 )); then
		for (( d=0 ; d<wm_desktop_count ; d++ )); do
			wm_desktop_monitor[d]=$primary
			declare -Ag "desktop_$d=( dirty 1 )"
			list_append monitor_$primary desktops $d
		done
	else
		for (( d=0 ; d<wm_desktop_count ; d++ )); do
			desktop_dirty $d
		done
	fi
}

focus_here() {
	#local windowid=$1
	#local root=$2
	local child=$3
	
	focus_window $child
}

focus_window() {
	local windowid=$1

	log 'focus_window %s\n' $windowid

	is_object window_$windowid || return

	local -n window=window_$windowid

	case ${window['type']} in
		tile|float)
			focuslist_add $windowid
			setfocus $windowid
			;;
		*)
			setfocus 0
			;;
	esac
}

focus_pointer() {
	x_send_query_pointer ${x_screen_0['root']} focus_here
}

move_focus() {
	local direction=$1
	local active=${x_screen_0['active']}
	[[ $active ]] || return
	local -n window=window_$active
	local windowid

	case $window['type'] in
		tile) windowid=${ ${wm_layout}_find_tile $active $direction; } ;;
		float) windowid=${ find_float $active $direction; } ;;
	esac

	[[ $windowid ]] && focus_window $windowid
}

find_float() {
	local windowid=$1
	local direction=$2

	# only called when window is on current desktop
	local -n focuslist=focuslist_$wm_current_desktop
	local count=${#focuslist[@]}
	local floats=()
	local pos current id

	for (( pos=0 ; pos<count ; pos++ )); do
		id=${focuslist[pos]}
		local -n window=window_$id
		[[ ${window['type']} == 'float' ]] || continue
		floats+=( $id )
		if (( focuslist[pos] == windowid )); then
			current=pos
		fi
	done
	[[ $current ]] || 
		die 'Window %s is not a float in the focuslist [%s]\n' \
			$windowid "${floats[*]}"

	count=${#floats[@]}

	case $direction in
		$W_Next|$W_Down|$W_Right|$W_Clockwise) 
			echo ${floats[current + 1 % count}]} ;;
		$W_Previous|$W_Up|$W_Left|$W_AntiClockwise)
			echo ${floats[count + current - 1 % count]} ;;
	esac
}

dynamic_find_tile() {
	local windowid=$1
	local direction=$2

	log 'find_tile from %s in direction %s\n' $windowid $direction

	# Will only be called if window is on current desktop
	local -n desktop=desktop_$wm_current_desktop

	local ids=( ${desktop['tiles']} )
	local count=${#ids[@]}
	log 'tile count=%d, tiles=[%s]' $count "${ids[*]}"

	(( count > 1 )) || return

	local pos
	for (( pos=0 ; pos<count ; pos++ )); do
		(( windowid == ids[pos] )) && break
	done
	(( pos < count )) || 
		die 'Window %s is not in tile list [%s]\n' \
			$windowid "${ids[*]}" 

	case $direction in
		$W_Left)
			(( pos )) && echo ${ids[0]} ;;
		$W_Right)
			(( pos == 0 )) && echo ${ids[1]} ;;
		$W_Previous|$W_AntiClockwise)
			echo ${ids[(count + pos - 1) % count]} ;;
		$W_Next|$W_Clockwise)
			echo ${ids[(pos + 1) % count]} ;;
		$W_Up)
			(( pos > 1 )) && echo ${ids[pos - 1]} ;;
		$W_Down)
			(( pos > 0 && pos < count - 1 )) &&
				echo ${ids[pos + 1]} ;;
	esac
}

move_reposiiton() {
	local active=${x_screen_0['active']}
	[[ $active ]] || return
	local -n window=window_$active
	case ${window['type']} in
		tile) ${wm_layout}_reposition_tile $active $direction;;
		float) reposition_float $active $direction;;
	esac
}

dynamic_reposition_tile() {
	local windowid=$1
	local direction=$2

	local tile=${ dynamic_find_tile $windowid $direction; }

	[[ $tile ]] || return

	local window_pos= dynamic_tile_pos $windowid
	local tile_pos=dynamic_tile_pos $tile

	case $direction in
		$W_Left)
			dynamic_rotate_tiles 1  $window_pos $tile_pos ;;
		$W_AntiClockwise)
			dynamic_rotate_tiles -1 ;;
		$W_Clockwise)
			dynamic_rotate_tiles 1 ;;
		*)
			dynamic_swap_tiles $window_pos $tile_pos ;;
	esac

	layout_desktop $wm_current_desktop
}



array_index() {
	local -n arr=$1
	local val=$2
	local len=${#arr[@]}
	local i

	for (( i=0 ; i<len ; i++ )); do
		echo $i && break
	done
}

swap_tiles() {
	local tile1=$1
	local tile2=$2

	[[ $tile1 && $tile2 && $tile1 != $tile2 ]] || return

	local -n window1=window_$tile1
	local -n window2=window_$tile2

	(( wm_current_desktop == window1['desktop'] && 
		wm_current_desktop == window2['desktop'] )) || return

	local -n desktop=desktop_$wm_current_desktop

	local tiles=( ${desktop['tiles']} )
	local i1=${ array_index tiles $tile1; }
	local i2=${ array_index tiles $tile2; }

	[[ $i1 && $i2 ]] || return

	tiles[i1]=$tile2
	tiles[i2]=$tile3

	desktop['tiles']=" ${tiles[*]} "

}







#######

connect_unixsocket() {
	local _fd=$1
	local _path=$2

	enable -f /usr/share/bashwm/lib/unixconnect.so unixconnect &&
		unixconnect -v $_fd $_path
}




dump_all() {
	local m

	log 'Screen:\n'
	log_array x_screen_0

	log 'Desktop_Monitors: <%s>\n' "${wm_desktop_monitor[*]}"

	for m in "${wm_monitors[@]}"; do
		log_monitor $m
		log '\n'
	done

	dump_problems
}

dump_problems() {
	local d desktops windows all_windows

	for m in "${wm_monitors[@]}"; do
		local -n monitor=monitor_$m
		desktops+=${monitor['desktops']}
	done
	for (( d=0 ; d<wm_desktop_count ; d++ )); do
		local -n desktop=desktop_$d
		windows+=" ${desktop['tiles']} ${desktop['floats']} "
		[[ " $desktops " =~ " $d " ]] && continue
		log 'Orphaned desktop %d (%s):\n' $d "$desktops"
		log_desktop $d
	done

	for w in "${!window_@}"; do
		local -n window=$w
		[[ ${window['type']} == tile || ${window['type']} == float ]] ||
			continue
		[[ $windows =~ " ${w#window_} " ]] && continue
		log 'Orphaned window:\n'
		log_array $w
	done
}

declare_window() {
	local windowid=$1

	declare -Ag window_$windowid="( $* )"
}

unset_window() {
	local windowid=$1

	unset 'window_$windowid'
}

link_append_ids() {
	local src=$1
	local srcid=$2
	local tgt=$3
	local tgtid=$4
	local tgts=${tgt}s

	local -n target=${tgt}_${tgtid}

	log 'link_append_ids: %s\n' "$*"

	if list_member ${src}_${srcid} ${tgts} ${tgtid}; then
		log '  ERROR: %s already in %s_%s[%s]\n' \
			${tgtid} ${src} ${srcid} ${tgts}
	fi
	if [[ ${target[$src]} ]]; then
		log '  ERROR: %s_%s[%s] is linked to %s_%s' \
			${tgt} ${tgtid} ${src} ${target[$src]}
	fi

	list_push ${src}_$srcid ${tgts} $tgtid
	target[$src]=$srcid
}

link_push_ids() {
	local src=$1
	local srcid=$2
	local tgt=$3
	local tgtid=$4
	local tgts=${tgt}s

	local -n target=${tgt}_${tgtid}

	log 'link_push_ids: %s\n' "$*"

	if list_member ${src}_${srcid} ${tgts} ${tgtid}; then
		log '  ERROR: %s already in %s_%s[%s]\n' \
			${tgtid} ${src} ${srcid} ${tgts}
	fi
	if [[ ${target[$src]} ]]; then
		log '  ERROR: %s_%s[%s] is linked to %s_%s' \
			${tgt} ${tgtid} ${src} ${target[$src]}
	fi

	list_push ${src}_$srcid ${tgts} $tgtid
	target[$src]=$srcid
}

unlink_ids() {
	local src=$1
	local srcid=$2
	local tgt=$3
	local tgtid=$4

	local -n target=${tgt}_${tgtid}

	log 'unlink_ids: %s\n' "$*"

	if ! list_member ${src}_${srcid} ${tgts} ${tgtid}; then
		log '  ERROR: %s not in %s_%s[%s]\n' \
			${tgtid} ${src} ${srcid} ${tgts}
	fi
	if [[ ${target[$src]} != $srcid ]]; then
		log '  ERROR: %s_%s[%s] is not linked to %s_%s (is %s)' \
			${tgt} ${tgtid} ${src} ${srcid} ${target[$src]:-empty} 
	fi

	list_remove ${src}_$srcid ${tgts} $tgtid
	unset 'target[$src]'
}

log_monitor() {
	local m=$1
	local d

	log 'Monitor:\n'
	log_array monitor_$m 

	local -n monitor=monitor_$m
	local desktops="${monitor['desktops']}"
	log 'Desktops: <%s>\n' "$desktops"
	for d in $desktops; do
		log_desktop $d
	done
}

log_desktop() {
	local d=$1
	local desktop t f

	log 'Desktop %s (on monitor %s):\n' $d ${wm_desktop_monitor[d]}

	log_array desktop_$d
	
	local -n desktop=desktop_$d
	log 'Tiled Windows: <%s>\n' "${desktop['tiles']}" 
	for t in ${desktop['tiles']}; do
		log 'Window:\n'
		log_array window_$t
	done
	log 'Floating Windows: <%s>\n' "${desktop['floats']}"
	for f in ${desktop['floats']}; do
		log 'Window:\n'
		log_array window_$f
	done
}

source_config() {
	local p
	if [[ $XDG_CONFIG_HOME ]]; then
		p="$XDG_CONFIG_HOME/bashwm"
	else 
		p="~/.config/bashwm"
	fi
	p+=':/etc/bashwm:/usr/share/bashwm'
	source -p "$p" config.sh 2>/dev/null || log 'Config file not found'
}

require() {
	while [[ $1 ]]; do
		if [[ -z ${wm_required[$1]} ]]; then

			source -p $wm_require_path "$1.sh" || 
				die 'Failed to load wm_required library: %s\n' "$1.sh"

			wm_required[$1]=1
		fi

		shift
	done
}


run() {
	cache_xa_names
	register_property_handlers

	x_open_display

	rr_get_monitors
	intern_atoms
	get_key_mappings	
	change_window_events ${x_screen_0['root']} $wm_root_events
	create_wmcheck_window

	x_when_sync adopt_windows
	[[ $autostart ]] && x_when_sync $autostart

	x_event_loop
}


export DISPLAY=${DISPLAY:-:${1:-0}}

LC_CTYPE=C

wm_require_path=/usr/share/bashwm/lib
declare -A wm_required

require xcore xrandr

declare -A wm_properties

wm_desktop_count=4
wm_current_desktop=0
wm_desktop_monitor=()

wm_border_width=1
wm_border_active=$(( 16#005577 ))
wm_border_inactive=$(( 16#444444 ))

W_NotMapped=0
W_MapRequested=1
W_Mapped=2
W_Unmapped=3

wm_property_change_handlers=()
wm_monitors=()

wm_layout=dynamic

wm_keycode_commands=()

wm_keysym_commands=(
	[XK_1]="$X_Mod4Mask:select_desktop 0,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 0,$((X_Mod4Mask|X_ControlMask)):desktop_to_monitor 0"
	[XK_2]="$X_Mod4Mask:select_desktop 1,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 1,$((X_Mod4Mask|X_ControlMask)):desktop_to_monitor 1"
	[XK_3]="$X_Mod4Mask:select_desktop 2,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 2,$((X_Mod4Mask|X_ControlMask)):desktop_to_monitor 2"
	[XK_4]="$X_Mod4Mask:select_desktop 3,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 3,$((X_Mod4Mask|X_ControlMask)):desktop_to_monitor 3"
	[XK_Return]="$X_Mod4Mask:new_terminal"
	[XK_b]="$X_Mod4Mask:new_browser"
	[XK_c]="$((X_Mod4Mask|X_ShiftMask)):delete_window"
	[XK_d]="$((X_Mod4Mask|X_ShiftMask)):dump_all"
	[XK_g]="$((X_Mod4Mask|X_ShiftMask)):request_get_monitors"
	[XK_q]="$((X_Mod4Mask|X_ShiftMask)):wm_exit"
	[XK_Up]="$X_Mod4Mask:swap_master"
	[XK_h]="$X_Mod4Mask:focus_left"
	[XK_j]="$X_Mod4Mask:focus_down"
	[XK_k]="$X_Mod4Mask:focus_up"
	[XK_l]="$X_Mod4Mask:focus_right"
	[XK_f]="$X_Mod4Mask:focus_pointer"
	[XK_p]="$X_Mod4Mask:show_menu"
)

wm_root_events=$(( X_SubstructureRedirectMask |
		    X_StructureNotifyMask |
		    X_SubstructureNotifyMask |
		    X_PropertyChangeMask ))

wm_client_events=$(( X_EnterWindowMask |
			X_FocusChangeMask |
			X_StructureNotifyMask |
			X_PropertyChangeMask ))

x_event_handlers[X_KeyPress]=handle_key_press
x_event_handlers[X_EnterNotify]=handle_enter_notify
x_event_handlers[X_FocusIn]=handle_focus_in
x_event_handlers[X_CreateNotify]=handle_create_notify
x_event_handlers[X_DestroyNotify]=handle_destroy_notify
x_event_handlers[X_UnmapNotify]=handle_unmap_notify
x_event_handlers[X_MapRequest]=handle_map_request
x_event_handlers[X_ConfigureNotify]=handle_configure_notify
x_event_handlers[X_ConfigureRequest]=handle_configure_request
x_event_handlers[X_PropertyNotify]=handle_property_notify
x_event_handlers[X_ClientMessage]=handle_client_message
x_event_handlers[X_Error]=handle_error

source_config

logfile=~/.cache/bashwm/bashwm-${DISPLAY#*:}.log
if [[ -f $logfile ]]; then
	# !PURE_BASH rm
	mv $logfile ${logfile}.old
else
	# !PURE_BASH mkdir
	mkdir -p ${logfile%/*}
fi

run &> $logfile
