#!/usr/bin/env bash

dsp=${1:-${DISPLAY:1}}

LC_CTYPE=C

. bashwm_xvars

write8() {
	local t=0
	(( $1 )) && printf -v t '%x' "$(( $1 & 16#FF ))"
	printf '%b' "\x$t"
}

write16() {
	local val=$1

	write8 $(( val >> 8 ))
	write8 $val
}

write32() {
	local val=$1

	write8 $(( val >> 24 ))
	write8 $(( val >> 16 ))
	write8 $(( val >> 8 ))
	write8 $val
}

writepad() {
	local i
	for (( i=0 ; i<$1 ; i++ )); do
		write8 0
	done
}

writepad4() {
	writepad $(( (4 - ($1%4))%4 ))
}


writechars() {
	local len=$1
	local chars=$2
	printf '%s' "$2"
}


read8() {
	local t

	(( read_count++ ))
	IFS= read -r -d '' -n 1 t
	if [[ -n $t ]]; then
		printf -v "$1" '%d' "'$t"
	else
		printf -v "$1" "0"
	fi
}

read16() {
	local b1 b2
	read8 b1
	read8 b2
	printf -v "$1" "$(( b2 + (b1 << 8) ))"
}

read32() {
	local b1 b2 b3 b4
	read8 b1
	read8 b2
	read8 b3
	read8 b4
	printf -v "$1" "$(( b4 + (b3 << 8) + (b2 << 16) + (b1 << 24) ))"
}

readchars() {
	local i c s

	for (( i=0 ; i<$1 ; i++ )); do
		(( read_count++ ))
		IFS= read -r -d '' -n 1 c
		if [[ -z $c ]]; then
			readpad $(( $1 - i - 1 ))
			break
		fi
		s="$s$c"
	done
	printf -v "$2" '%s' "$s"
}

readpad() {
	local pad i

	for (( i=0 ; i<$1 ; i++ )); do
		(( read_count++ ))
		IFS= read -r -d '' -n 1 pad
	done
}

readpad4() {
	readpad "$(( (4 - ($1%4))%4 ))"
}

readxauth() {
	local proto=256
	local addr="${HOSTNAME}"
	local display="${DISPLAY#*:}"
	local length

	while [[ $xauth_proto != $proto ||
			$xauth_addr != $addr ||
			$xauth_display != $display ]]; do
		read16 xauth_proto
		read16 length
		readchars $length xauth_addr
		read16 length
		readchars $length xauth_display
		read16 xauth_name_length 
		readchars $xauth_name_length xauth_name
		read16 xauth_data_length
		readchars $xauth_data_length xauth_data
	done
}


readxauth < "${XAUTHORITY:-~/.Xauthority}"

exec {xfd}<>/dev/tcp/127.0.0.1/$(( 6000+$dsp ))

lsb_first="$(( 16#42 ))"
msb_first="$(( 16#6C ))"
proto_major=11
proto_minor=0


send_setup() {
	write8 $lsb_first
	writepad 1
	write16 $proto_major
	write16 $proto_minor
	write16 18
	write16 16
	writepad 2
	writechars 18 "$xauth_name"
	writepad4 18
	writechars 16 "$xauth_data"
	writepad4 16
}

read_setup_leader() {
	read8 setup_success
	read8 setup_length
	read16 proto_major
	read16 proto_minor
	read16 extra_length
}

read_setup_failure() {
	readchars $setup_length setup_failure_reason
	readpad "$(( extra_length * 4 - setup_length ))"
}

declare -A screens

count_reads() {
	read_count=0
	while : ;do
		local foo
		read8 'foo'
		printf '%02x ' $foo
	done
}

read_setup_ok() {
	read32 release_number
	read32 resource_id_base
	read32 resource_id_mask
	read32 motion_buffer_size
	read16 vendor_length
	read16 max_request_length
	read8 no_of_screens
	read8 no_of_formats
	read8 image_byte_order
	read8 bitmap_byte_order
	read8 bitmap_scanline_unit
	read8 bitmap_scanline_pad
	read8 min_keycode
	read8 max_keycode
	readpad 4
	readchars $vendor_length vendor 
	readpad4 $vendor_length
	readpad $(( 8 * no_of_formats ))

	read_count=0

	for (( i=0 ; i<no_of_screens ; i++ )); do
		read32 root && screens[$i-root]=$root
		read32 colormap && screens[$i-colormap]=$colormap
		read32 white_pixel && screens[$i-white_pixel]=$white_pixel
		read32 black_pixel && screens[$i-black_pixel]=$black_pixel
		read32 input_masks && screens[$i-input_masks]=$input_masks
		read16 width_pixels && screens[$i-width_pixels]=$width_pixels
		read16 height_pixels && screens[$i-height_pixels]=$height_pixels
		read16 width_mm && screens[$i-width_mm]=$width_mm
		read16 height_mm && screens[$i-height_mm]=$height_mm
		read16 min_maps && screens[$i-min_maps]=$min_maps
		read16 max_maps && screens[$i-max_maps]=$max_maps
		read32 visual_id && screens[$i-root_visual]=$root_visual
		read8 backing_stores && screens[$i-backing_stores]=$backing_stores
		read8 save_unders && screens[$i-save_unders]=$save_unders
		read8 root_depth && screens[$i-root_depth]=$root_depth
		read8 no_of_depths && screens[$i-no_of_depths]=$no_of_depths
		for (( d=0 ; d<no_of_depths ; d++ )); do
			pfx=$i,$d
			read8 depth
			screens[$pfx-depth]=$depth
			readpad 1
			read16 no_of_visuals
			screens[$pfx-no_of_visuals]=$no_of_visuals
			readpad 4
			for (( v=0 ; v<no_of_visuals ; v++ )); do
				read32 visual_id
				pfx=$i,$d,$v
				screens[$pfx-visual_id]=$visual_id
				read8 class
				screens[$pfx-class]=$class
				read8 bits_per_rgb
				screens[$pfx-bits_per_rgb]=$bits_per_rgb
				read16 colormaps
				screens[$pfx-colormaps]=$colormaps
				read32 red_mask
				screens[$pfx-red_mask]=$red_mask
				read32 green_mask
				screens[$pfx-green_mask]=$green_mask
				read32 blue_mask
				screens[$pfx-blue_mask]=$blue_mask
				readpad 4
			done
		done
	done
}

beginrequest() {
	local opcode=$1
	local byte1=$2
	local req_length=$3
	local handler=${reply_handlers[$1]}

	(( sequence_number++ ))
	write8 $opcode
	write8 $byte1
	write16 $req_length
	[[ $handler ]] && request_map[sequence_number]=$handler 
}

send_change_window_events() {
	local root=screens[0-root]
	beginrequest $X_ChangeWindowAttributes 0 4
	write32 $root
	write32 $X_CWEventMask
	write32 $(( $X_SubstructureRedirectMask | 
		    $X_StructureNotifyMask |      
		    $X_SubstructureNotifyMask |   
		    $X_PropertyChangeMask ))
}

send_get_keyboard_mapping() {
	beginrequest $X_GetKeyboardMapping 0 2
	write8 $min_keycode
	write8 $(( 1 + max_keycode - min_keycode ))
	writepad 2
}

send_grab_key() {
	local keycode=$1
	local mask=$2

	beginrequest $X_GrabKey 0 4
	write32 $root
	write16 $mask
	write8 $keycode
	write8 1
	write8 1
	writepad 3
}

read_keyboard_mapping() {
	local keysyms_per=$1
	local keycodes=$(( 1 + max_keycode - min_keycode ))
	local key_mappings=$(( keysyms_per * keycodes ))
	local keycode keycodesym keycmds keycmda keycmd mask

	read32 reply_length
	(( reply_length == key_mappings )) ||
		die "Unexpected number of keboard mappings: " \
			"Got $reply_length, Expected $key_mappings"
	readpad 24

	for (( keycode=min_keycode ; keycode<=max_keycode ; keycode++ )); do
		# only interested in the first keysym
		read32 keycodesym
		readpad $(( 4 * (keysyms_per - 1) ))

		keycmds="${keysym_command_map[keycodesym]}"
		[[ $keycmds ]] || continue
		keycode_command_map[keycode]=$keycmds
	done

	for keycode in ${!keycode_command_map[@]}; do
		IFS=',' read -ra keycmds <<< "${keycode_command_map[keycode]}" 
		for keycmd in "${keycmds[@]}"; do
			mask="${keycmd%:*}"
			send_grab_key $keycode $mask
		done
	done
}
reply_handlers[X_GetKeyboardMapping]=read_keyboard_mapping

event_loop() {
	local input_type=1
	while (( input_type != X_Error )); do
		read8 input_type
		handler=${event_handlers[input_type]}
		if [[ $handler ]]; then
			$handler
		else
			# discard unwanted event data
			readpad 31
		fi
	done
}

handle_error() {
	read8 error_code
	read16 error_seq_no
	read32 error_data
	read16 error_major_op_code
	read8 error_minor_op_code
	readpad 21
}
event_handlers[X_Error]=handle_error

handle_reply() {
	read8 reply_byte
	read16 reply_seq_no
	handler=${request_map[reply_seq_no]}
	[[ $handler ]] || die "Unexpected reply: sequence number = $reply_seq_no"
	unset request_map[reply_seq_no]
	$handler $reply_byte $reply_seq_no
}
event_handlers[X_Reply]=handle_reply

handle_motion_notify() {
	# ignore for now
	readpad 31
	echo "handle_motion_notify" >>bashwm.log
}
event_handlers[X_MotionNotify]=handle_motion_notify

handle_enter_notify() {
	# ignore for now
	readpad 31
	echo "handle_enter_notify" >>bashwm.log
}
event_handlers[X_EnterNotify]=handle_enter_notify

handle_destroy_notify() {
	# ignore for now
	readpad 31
	echo "handle_destroy_notify" >>bashwm.log
}
event_handlers[X_DestroyNotify]=handle_destroy_notify

handle_button_press() {
	# ignore for now
	readpad 31
	echo "handle_button_press" >>bashwm.log
}
event_handlers[X_ButtonPress]=handle_button_press

handle_button_release() {
	# ignore for now
	readpad 31
	echo "handle_button_release" >>bashwm.log
}
event_handlers[X_ButtonRelease]=handle_button_release

handle_key_press() {
	local keycode keymask keycode_cmd keycmd mask cmd

	read8 keycode
	readpad 26
	read16 keymask
	readpad 2

	keycode_cmd="${keycode_command_map[keycode]}" 
	[[ $keycode_cmd ]] || return 0

	printf "%d:%d => %s\n" $keycode $keymask "$keycode_cmd" >> bashwm.log

	IFS=',' read -ra keycmds <<< "$keycode_cmd"
	for keycmd in "${keycmds[@]}"; do
		mask="${keycmd%:*}"
		(( mask == keymask )) || continue
		cmd="${keycmd#*:}"
		$cmd
		break
	done
}
event_handlers[X_KeyPress]=handle_key_press

handle_map_request() {
	# ignore for now
	readpad 31
	echo "handle_map_request" >>bashwm.log
}
event_handlers[X_MapRequest]=handle_map_request

handle_focus_in() {
	# ignore for now
	readpad 31
	echo "handle_focus_in" >>bashwm.log
}
event_handlers[X_FocusIn]=handle_focus_in

handle_focus_out() {
	# ignore for now
	readpad 31
	echo "handle_focus_out" >>bashwm.log
}
event_handlers[X_FocusOut]=handle_focus_out

new_terminal() {
	DISPLAY=:$dsp setsid -f /usr/local/bin/terminal
}


send_setup >&"$xfd"

#i=0
#while : ; do
#	(( ++i ))
#	read -r -d '' -n 1 -u $xfd char
#	printf '[ %d ] ' $?
#	if [[ -z $char ]]; then
#		printf '0\n'
#	else
#		printf '%d\n' "'${char}"
#	fi
#done
#exit 0

read_setup_leader <&"$xfd"

if (( $setup_success != 1 )); then
	read_setup_failure <&"$xfd"

	printf 'Setup Failed '
	(( $setup_success == 2 )) && printf '(Auth) '
	printf ': %s\n' "$setup_failure_reason"
	exit $setup_success
fi

echo "extra_length = $extra_length"

read_setup_ok <&"$xfd"

echo "read_count = $read_count"

echo "release number = $release_number"
echo "max_request_length = $max_request_length"
echo "vendor_length = $vendor_length"
echo "vendor = $vendor"
echo "screens = $no_of_screens"
echo "formats = $no_of_formats"
echo "keycodes = $min_keycode .. $max_keycode"

echo "width_pixels = ${screens[0-width_pixels]}"
echo "height_pixels = ${screens[0-height_pixels]}"
echo "width_mm = ${screens[0-width_mm]}"
echo "height_mm = ${screens[0-height_mm]}"

echo "root = ${screens[0-root]}"

declare -a keysym_command_map=(
	[$XK_1]="$X_Mod4Mask:select_desktop 1,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 1"
	[$XK_2]="$X_Mod4Mask:select_desktop 1,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 1"
	[$XK_3]="$X_Mod4Mask:select_desktop 1,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 1"
	[$XK_4]="$X_Mod4Mask:select_desktop 1,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 1"
	[$XK_Return]="$X_Mod4Mask:new_terminal"
	[$XK_b]="$X_Mod4Mask:new_browser"
	[$XK_p]="$X_Mod4Mask:show_menu"
)

send_change_window_events >&"$xfd"
send_get_keyboard_mapping >&"$xfd"

event_loop >&"$xfd" <&"$xfd"

if [[ $error_code ]]; then
	printf 'Error code: %d\n' $error_code
	printf 'Error seq_no: %d\n' $error_seq_no
	printf 'Error data: %04x\n' $error_data
	printf 'Error op code: %d:%d\n' $error_major_op_code $error_minor_op_code
fi
