#!/usr/bin/env bash

dsp=${1:-${DISPLAY:1}}

LC_CTYPE=C

. bashwm_xvars

>| bashwm.log

log() {
	printf "$@" >> bashwm.log
}

write8() {
	local t=0
	(( $1 )) && printf -v t '%x' "$(( $1 & 16#FF ))"
	printf '%b' "\x$t"
}

write16() {
	local val=$1

	write8 $(( val >> 8 ))
	write8 $val
}

write32() {
	local val=$1

	write8 $(( val >> 24 ))
	write8 $(( val >> 16 ))
	write8 $(( val >> 8 ))
	write8 $val
}

writepad() {
	local i
	for (( i=0 ; i<$1 ; i++ )); do
		write8 0
	done
}

pad4() {
	local l=$1
	echo $(( (4 - (l % 4)) % 4 ))
}

writepad4() {
	writepad $(pad4 $1)
}


writechars() {
	local len=$1
	local chars=$2
	printf '%s' "$2"
}

writebytes() {
	local len=$1
	local bytes=$2
	local byte_count=$(( ${#bytes}/2 ))
	local i b

	for (( i=0 ; i<byte_count ; i++ )); do
		b=$(( i*2 ))
		printf '%b' "\x${bytes:b:2}"
	done
	# If len > byte_count pad with nulls
	for (( i=byte_count ; i<len ; i++ )); do
		printf '%b' '\x00'
	done
}

read8() {
	local _t

	(( read_count++ ))
	IFS= read -r -d '' -n 1 _t
	if [[ -n $_t ]]; then
		printf -v "$1" '%d' "'$_t"
	else
		printf -v "$1" "0"
	fi
}

read16() {
	local _b1 _b2
	read8 _b1
	read8 _b2
	printf -v "$1" "$(( _b2 + (_b1 << 8) ))"
}

read32() {
	local _b1 _b2 _b3 _b4
	read8 _b1
	read8 _b2
	read8 _b3
	read8 _b4
	printf -v "$1" "$(( _b4 + (_b3 << 8) + (_b2 << 16) + (_b1 << 24) ))"
}

readchars() {
	local _i _c _s

	for (( _i=0 ; _i<$1 ; _i++ )); do
		(( read_count++ ))
		IFS= read -r -d '' -n 1 _c
		if [[ -z $_c ]]; then
			readpad $(( $1 - _i - 1 ))
			break
		fi
		_s="$_s$_c"
	done
	printf -v "$2" '%s' "$_s"
}

readbytes() {
	local _i _c _b _s

	for (( _i=0 ; _i<$1 ; _i++ )); do
		(( read_count++ ))
		IFS= read -r -d '' -n 1 _c
		if [[ -z $_c ]]; then
			_b='00'
		else
			printf -v _b '%d' "'$_c"
			printf -v _b '%02x' $_b
		fi
		_s+=$_b
	done

	printf -v "$2" $_s
}

readpad() {
	local pad i

	for (( i=0 ; i<$1 ; i++ )); do
		(( read_count++ ))
		IFS= read -r -d '' -n 1 pad
	done
}

readpad4() {
	readpad $(pad4 $1)
}

readxauth() {
	local proto=256
	local addr="${HOSTNAME}"
	local display="${DISPLAY#*:}"
	local length

	while [[ $xauth_proto != $proto ||
			$xauth_addr != $addr ||
			$xauth_display != $display ]]; do
		read16 xauth_proto
		read16 length
		readchars $length xauth_addr
		read16 length
		readchars $length xauth_display
		read16 xauth_name_length 
		readchars $xauth_name_length xauth_name
		read16 xauth_data_length
		readbytes $xauth_data_length xauth_data
	done
}


readxauth < "${XAUTHORITY:-~/.Xauthority}"

exec {xfd}<>/dev/tcp/127.0.0.1/$(( 6000+$dsp ))

lsb_first="$(( 16#42 ))"
msb_first="$(( 16#6C ))"
proto_major=11
proto_minor=0


send_setup() {
	write8 $lsb_first
	writepad 1
	write16 $proto_major
	write16 $proto_minor
	write16 18
	write16 16
	writepad 2
	writechars 18 "$xauth_name"
	writepad4 18
	writebytes 16 "$xauth_data"
	writepad4 16
}

read_setup_leader() {
	read8 setup_success
	read8 setup_length
	read16 proto_major
	read16 proto_minor
	read16 extra_length
}

read_setup_failure() {
	readchars $setup_length setup_failure_reason
	readpad "$(( extra_length * 4 - setup_length ))"
}

declare -A screens

count_reads() {
	read_count=0
	while : ;do
		local foo
		read8 'foo'
		printf '%02x ' $foo
	done
}

read_setup_ok() {
	read32 release_number
	read32 resource_id_base
	read32 resource_id_mask
	read32 motion_buffer_size
	read16 vendor_length
	read16 max_request_length
	read8 no_of_screens
	read8 no_of_formats
	read8 image_byte_order
	read8 bitmap_byte_order
	read8 bitmap_scanline_unit
	read8 bitmap_scanline_pad
	read8 min_keycode
	read8 max_keycode
	readpad 4
	readchars $vendor_length vendor 
	readpad4 $vendor_length
	readpad $(( 8 * no_of_formats ))

	read_count=0

	for (( i=0 ; i<no_of_screens ; i++ )); do
		read32 root && screens[$i-root]=$root
		read32 colormap && screens[$i-colormap]=$colormap
		read32 white_pixel && screens[$i-white_pixel]=$white_pixel
		read32 black_pixel && screens[$i-black_pixel]=$black_pixel
		read32 input_masks && screens[$i-input_masks]=$input_masks
		read16 width_pixels && screens[$i-width_pixels]=$width_pixels
		read16 height_pixels && screens[$i-height_pixels]=$height_pixels
		read16 width_mm && screens[$i-width_mm]=$width_mm
		read16 height_mm && screens[$i-height_mm]=$height_mm
		read16 min_maps && screens[$i-min_maps]=$min_maps
		read16 max_maps && screens[$i-max_maps]=$max_maps
		read32 visual_id && screens[$i-root_visual]=$root_visual
		read8 backing_stores && screens[$i-backing_stores]=$backing_stores
		read8 save_unders && screens[$i-save_unders]=$save_unders
		read8 root_depth && screens[$i-root_depth]=$root_depth
		read8 no_of_depths && screens[$i-no_of_depths]=$no_of_depths
		for (( d=0 ; d<no_of_depths ; d++ )); do
			pfx=$i,$d
			read8 depth
			screens[$pfx-depth]=$depth
			readpad 1
			read16 no_of_visuals
			screens[$pfx-no_of_visuals]=$no_of_visuals
			readpad 4
			for (( v=0 ; v<no_of_visuals ; v++ )); do
				read32 visual_id
				pfx=$i,$d,$v
				screens[$pfx-visual_id]=$visual_id
				read8 class
				screens[$pfx-class]=$class
				read8 bits_per_rgb
				screens[$pfx-bits_per_rgb]=$bits_per_rgb
				read16 colormaps
				screens[$pfx-colormaps]=$colormaps
				read32 red_mask
				screens[$pfx-red_mask]=$red_mask
				read32 green_mask
				screens[$pfx-green_mask]=$green_mask
				read32 blue_mask
				screens[$pfx-blue_mask]=$blue_mask
				readpad 4
			done
		done
	done
}

beginrequest() {
	local opcode=$1
	local byte1=$2
	local req_length=$3
	local handler=${4:-${reply_handlers[$1]}}

	(( sequence_number++ ))
	write8 $opcode
	write8 $byte1
	write16 $req_length
	[[ $handler ]] && request_map[sequence_number & 16#FFFF]=$handler 

	log 'Request %s %s (%s)\n' $opcode $req_length $sequence_number
}

send_change_window_events() {
	local window=$1
	local mask=$2

	beginrequest $X_ChangeWindowAttributes 0 4
	write32 $window
	write32 $X_CWEventMask
	write32 $mask
}

send_get_keyboard_mapping() {
	log '> GetKeyboardMapping\n'
	beginrequest $X_GetKeyboardMapping 0 2
	write8 $min_keycode
	write8 $(( 1 + max_keycode - min_keycode ))
	writepad 2
}

send_grab_key() {
	log '> GrabKey %s %s\n' $mask $keycode
	local keycode=$1
	local mask=$2

	beginrequest $X_GrabKey 0 4
	write32 $root
	write16 $mask
	write8 $keycode
	write8 1
	write8 1
	writepad 3
}

send_set_border_color() {
	log "> SetBorderColor $1 $2\n"
	local window=$1
	local border_pixel=$2

	beginrequest $X_ChangeWindowAttributes 0 4 
	write32 $window
	write32 $X_CWBorderPixel
	write32 $border_pixel
}

send_set_window_pos() {
	log '> SetWindowPos\n'
	local window=$1
	local x=$2
	local y=$3
	local width=$4
	local height=$5
	local border_width=$6

	beginrequest $X_ConfigureWindow 0 8
	write32 $window
	write16 $(( X_CWX | X_CWY | X_CWWidth | X_CWHeight | X_CWBorderWidth ))
	writepad 2
	write32 $(( x - border_width ))
	write32 $(( y - border_width ))
	write32 $(( width - (2 * border_width) ))
	write32 $(( height - (2 * border_width) ))
	write32 $border_width
}

send_map_window() {
	log '> MapWindow\n'
	local window=$1

	beginrequest $X_MapWindow 0 2
	write32 $window
}

send_intern_atom() {
	local name=$1
	local name_len=${#name}
	local name_pad=$(pad4 name_len)
	local req_len=$(( 2 + (name_len + name_pad) / 4 ))
	
	beginrequest $X_InternAtom 0 $req_len "read_intern_atom $name"
	write16 $name_len
	writepad 2
	writechars $name_len $name
	writepad $name_pad
}

read_keyboard_mapping() {
	local keysyms_per=$1
	local keycodes=$(( 1 + max_keycode - min_keycode ))
	local key_mappings=$(( keysyms_per * keycodes ))
	local keycode keycodesym keycmds keycmda keycmd mask

	read32 reply_length
	(( reply_length == key_mappings )) ||
		die "Unexpected number of keboard mappings: " \
			"Got $reply_length, Expected $key_mappings"
	readpad 24

	for (( keycode=min_keycode ; keycode<=max_keycode ; keycode++ )); do
		# only interested in the first keysym
		read32 keycodesym
		readpad $(( 4 * (keysyms_per - 1) ))

		keycmds="${keysym_command_map[keycodesym]}"
		[[ $keycmds ]] || continue
		keycode_command_map[keycode]=$keycmds
	done

	for keycode in ${!keycode_command_map[@]}; do
		IFS=',' read -ra keycmds <<< "${keycode_command_map[keycode]}" 
		for keycmd in "${keycmds[@]}"; do
			mask="${keycmd%:*}"
			send_grab_key $keycode $mask
		done
	done
}
reply_handlers[X_GetKeyboardMapping]=read_keyboard_mapping

declare -A atoms
current_desktop=0
desktop_count=4
read_intern_atom() {
	local name=$1

	readpad 4
	read32 atom
	readpad 20

	[[ ${name::1} == '_' ]] || name="_$name"

	printf -v "XA$name" $atom

	case $name in
		_NET_CURRENT_DESKTOP) 
			send_change_property $root $atom $XA_CARDINAL 32 1 $current_desktop 
			;;
		_NET_NUMBER_OF_DESKTOPS) 
			send_change_property $root $atom $XA_CARDINAL 32 1 $desktop_count
			;;
	esac
}

send_change_property() {
	local window=$1
	local prop_atom=$2
	local prop_type=$3
	local prop_bits=$4
	local prop_count=$5
	local bytes=$(( prop_count * prop_bits / 8 ))
	local pad=$(pad4 $bytes)
	local req_len=$(( 6 + (bytes + pad) / 4 ))

	shift 5
	local prop_value=( $@ )

	beginrequest $X_ChangeProperty $X_PropModeReplace $req_len
	write32 $window
	write32 $prop_atom
	write32 $prop_type
	write8 $prop_bits
	writepad 3
	write32 $prop_count

	if (( prop_type == XA_UTF8_STRING )); then
		writechars $prop_count $prop_value
	else
		for (( i=0 ; i<$prop_count ; i++ )); do
			write$prop_bits ${prop_value[i]}
		done
	fi
	writepad $pad
}

send_get_property() {
	local window=$1
	local atom=$2
	local atom_type=$3
	local length=$4
	local start=${5:-0}

	beginrequest $X_GetProperty 0 6 "read_get_property $window $atom $start"
	write32 $window
	write32 $atom
	write32 $atom_type
	write32 $start
	write32 $length
}


read_get_property() {
	local window=$1
	local atom=$2
	local start=$3
	local format=$4
	local reply_len atom_type length bytes_after
	local item val byte_count

	read32 reply_len
	read32 atom_type
	read32 bytes_after
	read32 length
	readpad 12

	(( $length  )) || return

	local -n window="window_$window"

	if (( $start )); then
		val=" ${window[$atom]}"
	fi

	if [[ $atom_type == $WA_STRING ]]; then
		readchars $length item
		val+="$item"
	else
		for (( i=0 ; i < length ; i++ )); do
			read${format} item
			val+=" $item"
		done
		val=${val:1}
	fi
	byte_count=$(( length * format / 8 ))
	readpad4 $byte_count

	window[$atom]="$val"

	(( bytes_after )) || return
	
	(( start += byte_count ))
	(( bytes_after -= byte_count ))

	send_get_property $window $atom $atom_type $bytes_after $start
}

send_delete_property() {
	local window=$1
	local atom=$2

	beginrequest $X_DeleteProperty 0 3
	write32 $window
	write32 $atom
}

allocate_id() {
	if (( last_id )); then
		(( last_id++ ))
	else
		last_id=1
		while (( ! last_id & resource_id_mask )); do
			(( last_id <<= 1))
		done
	fi

	echo $(( resource_id_base | last_id ))
}

add_check_window() {
	check_window=$(allocate_id)
	log 'Check window id=%s\n' $check_window

	beginrequest $X_CreateWindow 0 8
	write32 $check_window
	write32 $root
	write16 0
	write16 0
	write16 1
	write16 1
	write16 0
	write16 $X_InputOnly
	write32 $X_CopyFromParent
	write32 0
}

set_check_window_props() {
	local supported

	send_change_property $check_window $XA_NET_SUPPORTING_WM_CHECK \
		$XA_WINDOW 32 1 $check_window
	send_change_property $check_window $XA_NET_WM_NAME \
		$XA_UTF8_STRING 8 6 'bashwm'
	send_change_property $root $XA_NET_SUPPORTING_WM_CHECK \
		$XA_WINDOW 32 1 $check_window
	send_delete_property $root $XA_NET_CLIENT_LIST

	supported=( $XA_NET_CURRENT_DESKTOP $XA_NET_NUMBER_OF_DESKTOPS \
		$XA_NET_ACTIVE_WINDOW $XA_NET_SUPPORTED $XA_NET_WM_NAME \
		$XA_NET_WM_STATE $XA_NET_SUPPORTING_WM_CHECK \
		$XA_NET_WM_STATE_FULLSCREEN $XA_NET_WM_WINDOW_TYPE \
		$XA_NET_WM_WINDOW_TYPE_DOCK $XA_NET_WM_WINDOW_TYPE_NORMAL \
		$XA_NET_CLIENT_LIST )

	send_change_property $root $XA_NET_SUPPORTED \
		$XA_ATOM 32 ${#supported[@]} ${supported[@]}
	
}

event_loop() {
	local input_type=1
	while (( input_type != X_Error )); do
		read8 input_type

		log '< InputType %s\n' $input_type
		handler=${event_handlers[input_type & 16#7F]}
		if [[ $handler ]]; then
			log '< %s\n' $handler
			$handler $input_type
		else
			# discard unwanted event data
			readpad 31
		fi

	done
}

handle_error() {
	read8 error_code
	read16 error_seq_no
	read32 error_data
	read16 error_major_op_code
	read8 error_minor_op_code
	readpad 21
}
event_handlers[X_Error]=handle_error

handle_reply() {
	read8 reply_byte
	read16 reply_seq_no
	handler=${request_map[reply_seq_no]}
	[[ $handler ]] || die "Unexpected reply: sequence number = $reply_seq_no"
	unset request_map[reply_seq_no]
	log 'Reply %s (%s)\n' "$handler" "$reply_seq_no" 
	$handler $reply_byte $reply_seq_no

	handle_after_reply $reply_seq_no
}
event_handlers[X_Reply]=handle_reply

handle_after_reply() {
	local seq_no=$1
	local actions len lenlen action cmd
	if [[ -v after_replies[seq_no] ]]; then
		actions="${after_replies[seq_no]}"
		while (( ${#actions} )); do
			len="${actions%%(*}"
			lenlen=${#len}
			action="${actions:$lenlen:$len}"
			actions="${actions:(( lenlen + len ))}"
			declare -a cmd="$action"
			"${cmd[@]}"
		done
	fi
}

count_bits() {
	local mask=$1
	local count=0
	while (( mask )); do
		(( count+=mask&1, mask>>=1 ))
	done
	echo $count
}

handle_configure_notify() {
	local window
	readpad 7
	read32 window
	readpad 20

	log 'ConfigureNotify for window %s\n' $window
}
event_handlers[X_ConfigureNotify]=handle_configure_notify

handle_create_notify() {
	local window x y width height border_width override_redirect
	readpad 7
	read32 window
	read16 x
	read16 y
	read16 width
	read16 height
	read16 border_width
	read8 override_redirect
	readpad 9

	log 'CreateNotify for window %s, override_redirect %s\n' $window $override_redirect

	(( override_redirect )) && return

	[[ $window == $check_window ]] && set_check_window_props

	declare -Ag "window_$window=(x $x y $y width $width height $height border_width $border_width)"
}
event_handlers[X_CreateNotify]=handle_create_notify

handle_map_notify() {
	local window override_redirect
	readpad 7
	read32 window
	read8 override_redirect
	readpad 19

	log 'MapNotify for window %s, override_redirect %s\n' $window $override_redirect
}
event_handlers[X_MapNotify]=handle_map_notify

handle_configure_request() {
	local stack_mode parent window sibling 
	local x y width height border_width value_mask n

	read8 stack_mode
	readpad 2
	read32 parent
	read32 window
	read32 sibling
	read16 x
	read16 y
	read16 width
	read16 height
	read16 border_width
	read16 value_mask
	readpad 4

	log 'ConfigureRequest for window %s\n' $window

	local -n win="window_$window"

	n=$(count_bits $value_mask)
	beginrequest X_ConfigureWindow 0 $(( 3+n ))
	write32 $window
	write16 $value_mask
	writepad 2
	(( $value_mask & $X_CWX )) && 
		write32 $x && 
		win[x]=$x
	(( $value_mask & $X_CWY )) && 
		write32 $y && 
		win[y]=$y
	(( $value_mask & $X_CWWidth )) && 
		write32 $width &&
		win[width]=$width
	(( $value_mask & $X_CWHeight )) &&
		write32 $height &&
		win[height]=$height
	(( $value_mask & $X_CWBorderWidth )) &&
		write32 $border_width &&
		win[border_width]=$border_width
	(( $value_mask & $X_CWSibling )) && 
		write32 $sibling
	(( $value_mask & $X_CWStackMode )) && 
		write32 $stack_mode
}
event_handlers[X_ConfigureRequest]=handle_configure_request

handle_motion_notify() {
	# ignore for now
	readpad 31
	log "handle_motion_notify"
}
event_handlers[X_MotionNotify]=handle_motion_notify

handle_enter_notify() {
	# ignore for now
	readpad 31
	log 'handle_enter_notify\n'
}
event_handlers[X_EnterNotify]=handle_enter_notify

handle_destroy_notify() {
	# ignore for now
	readpad 31
	log 'handle_destroy_notify\n'
}
event_handlers[X_DestroyNotify]=handle_destroy_notify

handle_button_press() {
	# ignore for now
	readpad 31
	log 'handle_button_press\n'
}
event_handlers[X_ButtonPress]=handle_button_press

handle_button_release() {
	# ignore for now
	readpad 31
	log 'handle_button_release\n'
}
event_handlers[X_ButtonRelease]=handle_button_release

handle_key_press() {
	local keycode keymask keycode_cmd keycmd mask cmd

	read8 keycode
	readpad 26
	read16 keymask
	readpad 2

	keycode_cmd="${keycode_command_map[keycode]}" 
	[[ $keycode_cmd ]] || return 0

	IFS=',' read -ra keycmds <<< "$keycode_cmd"
	for keycmd in "${keycmds[@]}"; do
		mask="${keycmd%:*}"
		(( mask == keymask )) || continue
		cmd="${keycmd#*:}"
		$cmd
		break
	done
}
event_handlers[X_KeyPress]=handle_key_press

add_window() {
	local x=0
	local y=0
	local width=$width_pixels
	local height=$height_pixels

	echo $x $y $width $height
}

after_reply() {
	local cmd="(${@@Q})"
	local len=${#cmd}
	

	after_replies[sequence_number]+="${len}${cmd}"
}


handle_map_request() {
	local window

	readpad 7
	read32 window
	readpad 20

	log 'MapRequest for window %s\n' $window

	if [[ ! -v "window_$window"[$XA_NET_WM_WINDOW_TYPE] ]]; then
		send_get_property $window $XA_NET_WM_WINDOW_TYPE $XA_ATOM 1
		send_get_property $window $XA_NET_WM_STRUT_PARTIAL $XA_CARDINAL 12
		send_get_property $window $XA_WM_TRANSIENT_FOR $XA_WINDOW 1
		send_get_property $window $XA_WM_NORMAL_HINTS $XA_WM_SIZE_HINTS 18
		send_get_property $window $XA_WM_HINTS $XA_WM_HINTS 9
		after_reply map_window $window
		send_change_window_events $window $client_events
	else
		map_window $window
	fi
}
event_handlers[X_MapRequest]=handle_map_request

map_window() {
	local window=$1
	pos=( $(add_window) )
	send_set_border_color $window $(( 16#005577 )) # $focus_border
	send_set_window_pos $window ${pos[@]} 2 #$border_width
	send_map_window $window
}

handle_unmap_notify() {
	local window

	readpad 7
	read32 window
	readpad 20

	log 'UnmapNotify for window %s\n' $window

	remove_window $window
}


handle_focus_in() {
	# ignore for now
	readpad 31
	log 'handle_focus_in\n'
}
event_handlers[X_FocusIn]=handle_focus_in

handle_focus_out() {
	# ignore for now
	readpad 31
	log 'handle_focus_out\n'
}
event_handlers[X_FocusOut]=handle_focus_out

handle_client_message() {
	local format window atom 
	local value=0

	read8 format
	readpad 2
	read32 window
	read32 atom
	case $format in
		8) read8 value; readpad 19 ;;
		16) read16 value; readpad 18 ;;
		32) read32 value; readpad 16 ;;
		*) log 'Bad client message format %s\n' $format; readpad 20 ;;
	esac
	log 'ClientMessage %s %s %s %s\n' $format $window $atom $value
	(( atom == XA_NET_CURRENT_DESKTOP )) && select_desktop $value
}
event_handlers[X_ClientMessage]=handle_client_message

intern_atoms() {
	send_intern_atom UTF8_STRING
	send_intern_atom _NET_CURRENT_DESKTOP
	send_intern_atom _NET_NUMBER_OF_DESKTOPS
	send_intern_atom _NET_SUPPORTED
	send_intern_atom _NET_ACTIVE_WINDOW
	send_intern_atom _NET_SUPPORTING_WM_CHECK
	send_intern_atom _NET_WM_NAME
	send_intern_atom _NET_WM_STATE
	send_intern_atom _NET_WM_STATE_FULLSCREEN
	send_intern_atom _NET_WM_WINDOW_TYPE
	send_intern_atom _NET_WM_WINDOW_TYPE_NORMAL
	send_intern_atom _NET_WM_WINDOW_TYPE_DOCK
	send_intern_atom _NET_WM_STRUCT_PARTIAL
	send_intern_atom _NET_CLIENT_LIST
}

select_desktop() {
	local desktop=$1

	[[ $current_desktop != $desktop ]] || return

	send_change_property $root $XA_NET_CURRENT_DESKTOP \
		$XA_CARDINAL 32 1 $desktop
	
	hide_desktop $current_desktop
	current_desktop=$desktop
	show_desktop $current_desktop
}

hide_desktop() {
	:
}

show_desktop() {
	:
}

move_to_desktop() {
	:
}

spawn() {
	export DISPLAY=:$dsp
	/usr/bin/env --default-signal -C "$HOME" setsid -f "$@"
}

new_terminal() {
	spawn /usr/local/bin/terminal
}

new_browser() {
	spawn /usr/local/bin/browser
}

show_menu() {
	spawn /usr/local/bin/dmenu
}


send_setup >&"$xfd"

#i=0
#while : ; do
#	(( ++i ))
#	read -r -d '' -n 1 -u $xfd char
#	printf '[ %d ] ' $?
#	if [[ -z $char ]]; then
#		printf '0\n'
#	else
#		printf '%d\n' "'${char}"
#	fi
#done
#exit 0

read_setup_leader <&"$xfd"

if (( $setup_success != 1 )); then
	read_setup_failure <&"$xfd"

	printf 'Setup Failed '
	(( $setup_success == 2 )) && printf '(Auth) '
	printf ': %s\n' "$setup_failure_reason"
	exit $setup_success
fi

printf 'extra_length = $extra_length\n'

read_setup_ok <&"$xfd"

printf 'read_count = $read_count\n'

printf 'release number = $release_number\n'
printf 'max_request_length = $max_request_length\n'
printf 'vendor_length = $vendor_length\n'
printf 'vendor = $vendor\n'
printf 'screens = $no_of_screens\n'
printf 'formats = $no_of_formats\n'
printf 'keycodes = $min_keycode .. $max_keycode\n'

printf 'width_pixels = ${screens[0-width_pixels]}\n'
printf 'height_pixels = ${screens[0-height_pixels]}\n'
printf 'width_mm = ${screens[0-width_mm]}\n'
printf 'height_mm = ${screens[0-height_mm]}\n'

printf 'root = ${screens[0-root]}\n'

declare -a keysym_command_map=(
	[$XK_1]="$X_Mod4Mask:select_desktop 0,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 0"
	[$XK_2]="$X_Mod4Mask:select_desktop 1,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 1"
	[$XK_3]="$X_Mod4Mask:select_desktop 2,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 2"
	[$XK_4]="$X_Mod4Mask:select_desktop 3,$((X_Mod4Mask|X_ShiftMask)):move_to_desktop 3"
	[$XK_Return]="$X_Mod4Mask:new_terminal"
	[$XK_b]="$X_Mod4Mask:new_browser"
	[$XK_p]="$X_Mod4Mask:show_menu"
)

root_events=$(( $X_SubstructureRedirectMask | 
		    $X_StructureNotifyMask |      
		    $X_SubstructureNotifyMask |   
		    $X_PropertyChangeMask ))

client_events=$(( $X_EnterWindowMask |
			$X_FocusChangeMask |
			$X_StructureNotifyMask |
			$X_PropertyChangeMask ))

send_change_window_events $root $root_events >&"$xfd"
send_get_keyboard_mapping >&"$xfd"
intern_atoms >&"$xfd"
add_check_window >&"$xfd"

event_loop >&"$xfd" <&"$xfd"

if [[ $error_code ]]; then
	printf 'Error code: %d\n' $error_code
	printf 'Error seq_no: %d\n' $error_seq_no
	printf 'Error data: %04x\n' $error_data
	printf 'Error op code: %d:%d\n' $error_major_op_code $error_minor_op_code
fi
